/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AddEimResult.h"

static asn_oer_constraints_t asn_OER_type_AddEimResult_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_AddEimResult_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_AddEimResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AddEimResult, choice.associationToken),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associationToken"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AddEimResult, choice.addEimResultCode),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"addEimResultCode"
		},
};
static const unsigned asn_MAP_AddEimResult_to_canonical_1[] = { 1, 0 };
static const unsigned asn_MAP_AddEimResult_from_canonical_1[] = { 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_AddEimResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* addEimResultCode */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 } /* associationToken */
};
asn_CHOICE_specifics_t asn_SPC_AddEimResult_specs_1 = {
	sizeof(struct AddEimResult),
	offsetof(struct AddEimResult, _asn_ctx),
	offsetof(struct AddEimResult, present),
	sizeof(((struct AddEimResult *)0)->present),
	asn_MAP_AddEimResult_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_AddEimResult_to_canonical_1,
	asn_MAP_AddEimResult_from_canonical_1,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AddEimResult = {
	"AddEimResult",
	"AddEimResult",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_AddEimResult_constr_1, &asn_PER_type_AddEimResult_constr_1, CHOICE_constraint },
	asn_MBR_AddEimResult_1,
	2,	/* Elements count */
	&asn_SPC_AddEimResult_specs_1	/* Additional specs */
};

