/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AlertData_H_
#define	_AlertData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MetadataUpdateEnabledProfile.h"
#include "ServerWithPendingOperation.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlertData_PR {
	AlertData_PR_NOTHING,	/* No components present */
	AlertData_PR_metadataUpdateEnabledProfile,
	AlertData_PR_pendingOperationAlert
	/* Extensions may appear below */
	
} AlertData_PR;

/* AlertData */
typedef struct AlertData {
	AlertData_PR present;
	union AlertData_u {
		MetadataUpdateEnabledProfile_t	 metadataUpdateEnabledProfile;
		ServerWithPendingOperation_t	 pendingOperationAlert;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlertData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlertData;

#ifdef __cplusplus
}
#endif

#endif	/* _AlertData_H_ */
#include <asn_internal.h>
