/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AlertData.h"

static asn_oer_constraints_t asn_OER_type_AlertData_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_AlertData_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_AlertData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlertData, choice.metadataUpdateEnabledProfile),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MetadataUpdateEnabledProfile,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"metadataUpdateEnabledProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlertData, choice.pendingOperationAlert),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ServerWithPendingOperation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pendingOperationAlert"
		},
};
static const ber_tlv_tag_t asn_DEF_AlertData_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (74 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AlertData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* metadataUpdateEnabledProfile */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pendingOperationAlert */
};
static asn_CHOICE_specifics_t asn_SPC_AlertData_specs_1 = {
	sizeof(struct AlertData),
	offsetof(struct AlertData, _asn_ctx),
	offsetof(struct AlertData, present),
	sizeof(((struct AlertData *)0)->present),
	asn_MAP_AlertData_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AlertData = {
	"AlertData",
	"AlertData",
	&asn_OP_CHOICE,
	asn_DEF_AlertData_tags_1,
	sizeof(asn_DEF_AlertData_tags_1)
		/sizeof(asn_DEF_AlertData_tags_1[0]), /* 1 */
	asn_DEF_AlertData_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlertData_tags_1)
		/sizeof(asn_DEF_AlertData_tags_1[0]), /* 1 */
	{ &asn_OER_type_AlertData_constr_1, &asn_PER_type_AlertData_constr_1, CHOICE_constraint },
	asn_MBR_AlertData_1,
	2,	/* Elements count */
	&asn_SPC_AlertData_specs_1	/* Additional specs */
};

