/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AuthenticateClientOkRpm_H_
#define	_AuthenticateClientOkRpm_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SmdpSigned3.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientOkRpm */
typedef struct AuthenticateClientOkRpm {
	TransactionId_t	 transactionId;
	SmdpSigned3_t	 smdpSigned3;
	OCTET_STRING_t	 smdpSignature3;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOkRpm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkRpm;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkRpm_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOkRpm_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientOkRpm_H_ */
#include <asn_internal.h>
