/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AuthenticateClientOkEs11V3_H_
#define	_AuthenticateClientOkEs11V3_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SmdsSigned2.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientOkEs11V3 */
typedef struct AuthenticateClientOkEs11V3 {
	TransactionId_t	 transactionId;
	SmdsSigned2_t	 smdsSigned2;
	OCTET_STRING_t	 smdsSignature2;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOkEs11V3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkEs11V3;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkEs11V3_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOkEs11V3_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientOkEs11V3_H_ */
#include <asn_internal.h>
