/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AuthenticateClientOkDelayedDeviceChange_H_
#define	_AuthenticateClientOkDelayedDeviceChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SmdpSigned6.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientOkDelayedDeviceChange */
typedef struct AuthenticateClientOkDelayedDeviceChange {
	TransactionId_t	 transactionId;
	SmdpSigned6_t	 smdpSigned6;
	OCTET_STRING_t	 smdpSignature6;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOkDelayedDeviceChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkDelayedDeviceChange;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkDelayedDeviceChange_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOkDelayedDeviceChange_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientOkDelayedDeviceChange_H_ */
#include <asn_internal.h>
