/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AuthenticateClientOkDeviceChange.h"

asn_TYPE_member_t asn_MBR_AuthenticateClientOkDeviceChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDeviceChange, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDeviceChange, smdpSigned4),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDeviceChange, smdpSignature4),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature4"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticateClientOkDeviceChange, serviceProviderMessageForDc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalisedTextMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceProviderMessageForDc"
		},
};
static const int asn_MAP_AuthenticateClientOkDeviceChange_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_AuthenticateClientOkDeviceChange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateClientOkDeviceChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* smdpSigned4 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 2, 0, 0 }, /* smdpSignature4 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 } /* serviceProviderMessageForDc */
};
asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkDeviceChange_specs_1 = {
	sizeof(struct AuthenticateClientOkDeviceChange),
	offsetof(struct AuthenticateClientOkDeviceChange, _asn_ctx),
	asn_MAP_AuthenticateClientOkDeviceChange_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_AuthenticateClientOkDeviceChange_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkDeviceChange = {
	"AuthenticateClientOkDeviceChange",
	"AuthenticateClientOkDeviceChange",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateClientOkDeviceChange_tags_1,
	sizeof(asn_DEF_AuthenticateClientOkDeviceChange_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkDeviceChange_tags_1[0]), /* 1 */
	asn_DEF_AuthenticateClientOkDeviceChange_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateClientOkDeviceChange_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkDeviceChange_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AuthenticateClientOkDeviceChange_1,
	4,	/* Elements count */
	&asn_SPC_AuthenticateClientOkDeviceChange_specs_1	/* Additional specs */
};

