/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "AuthenticateClientOkRpm.h"

asn_TYPE_member_t asn_MBR_AuthenticateClientOkRpm_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkRpm, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkRpm, smdpSigned3),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkRpm, smdpSignature3),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature3"
		},
};
static const ber_tlv_tag_t asn_DEF_AuthenticateClientOkRpm_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateClientOkRpm_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* smdpSigned3 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 2, 0, 0 }, /* smdpSignature3 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* transactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkRpm_specs_1 = {
	sizeof(struct AuthenticateClientOkRpm),
	offsetof(struct AuthenticateClientOkRpm, _asn_ctx),
	asn_MAP_AuthenticateClientOkRpm_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkRpm = {
	"AuthenticateClientOkRpm",
	"AuthenticateClientOkRpm",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateClientOkRpm_tags_1,
	sizeof(asn_DEF_AuthenticateClientOkRpm_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkRpm_tags_1[0]), /* 1 */
	asn_DEF_AuthenticateClientOkRpm_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateClientOkRpm_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkRpm_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_AuthenticateClientOkRpm_1,
	3,	/* Elements count */
	&asn_SPC_AuthenticateClientOkRpm_specs_1	/* Additional specs */
};

