/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_AuthenticateClientOkDeviceChange_H_
#define	_AuthenticateClientOkDeviceChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SmdpSigned4.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LocalisedTextMessage;

/* AuthenticateClientOkDeviceChange */
typedef struct AuthenticateClientOkDeviceChange {
	TransactionId_t	 transactionId;
	SmdpSigned4_t	 smdpSigned4;
	OCTET_STRING_t	 smdpSignature4;
	struct LocalisedTextMessage	*serviceProviderMessageForDc	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOkDeviceChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkDeviceChange;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkDeviceChange_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOkDeviceChange_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LocalisedTextMessage.h"

#endif	/* _AuthenticateClientOkDeviceChange_H_ */
#include <asn_internal.h>
