/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_BoundProfilePackage_H_
#define	_BoundProfilePackage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitialiseSecureChannelRequest.h"
#include "BoundProfilePackage-87tlv.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "BoundProfilePackage-88tlv.h"
#include "BoundProfilePackage-86tlv.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BoundProfilePackage */
typedef struct BoundProfilePackage {
	InitialiseSecureChannelRequest_t	 initialiseSecureChannelRequest;
	struct BoundProfilePackage__firstSequenceOf87 {
		A_SEQUENCE_OF(BoundProfilePackage_87tlv_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} firstSequenceOf87;
	struct BoundProfilePackage__sequenceOf88 {
		A_SEQUENCE_OF(BoundProfilePackage_88tlv_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sequenceOf88;
	struct BoundProfilePackage__secondSequenceOf87 {
		A_SEQUENCE_OF(BoundProfilePackage_87tlv_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *secondSequenceOf87;
	struct BoundProfilePackage__sequenceOf86 {
		A_SEQUENCE_OF(BoundProfilePackage_86tlv_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sequenceOf86;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoundProfilePackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage;
extern asn_SEQUENCE_specifics_t asn_SPC_BoundProfilePackage_specs_1;
extern asn_TYPE_member_t asn_MBR_BoundProfilePackage_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _BoundProfilePackage_H_ */
#include <asn_internal.h>
