/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../asn/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CancelSessionRequestEsipa_H_
#define	_CancelSessionRequestEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "CancelSessionResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CancelSessionRequestEsipa */
typedef struct CancelSessionRequestEsipa {
	TransactionId_t	 transactionId;
	CancelSessionResponse_t	 cancelSessionResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CancelSessionRequestEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CancelSessionRequestEsipa;
extern asn_SEQUENCE_specifics_t asn_SPC_CancelSessionRequestEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_CancelSessionRequestEsipa_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CancelSessionRequestEsipa_H_ */
#include <asn_internal.h>
