/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CheckEventResponse_H_
#define	_CheckEventResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CheckEventOk.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CheckEventResponse_PR {
	CheckEventResponse_PR_NOTHING,	/* No components present */
	CheckEventResponse_PR_checkEventOk,
	CheckEventResponse_PR_checkEventError
	/* Extensions may appear below */
	
} CheckEventResponse_PR;
typedef enum CheckEventResponse__checkEventError {
	CheckEventResponse__checkEventError_invalidDsAddress	= 1,
	CheckEventResponse__checkEventError_eventCheckingNotSupported	= 2,
	CheckEventResponse__checkEventError_expiredEcid	= 3,
	CheckEventResponse__checkEventError_unknownEcid	= 4,
	CheckEventResponse__checkEventError_invalidInputData	= 124,
	CheckEventResponse__checkEventError_missingInputData	= 125,
	CheckEventResponse__checkEventError_functionProviderBusy	= 126,
	CheckEventResponse__checkEventError_undefinedError	= 127
} e_CheckEventResponse__checkEventError;

/* CheckEventResponse */
typedef struct CheckEventResponse {
	CheckEventResponse_PR present;
	union CheckEventResponse_u {
		CheckEventOk_t	 checkEventOk;
		long	 checkEventError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CheckEventResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CheckEventResponse;
extern asn_CHOICE_specifics_t asn_SPC_CheckEventResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_CheckEventResponse_1[2];
extern asn_per_constraints_t asn_PER_type_CheckEventResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CheckEventResponse_H_ */
#include <asn_internal.h>
