/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CheckEventOk_H_
#define	_CheckEventOk_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CheckEventOk */
typedef struct CheckEventOk {
	BOOLEAN_t	 isPendingEvent;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CheckEventOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CheckEventOk;
extern asn_SEQUENCE_specifics_t asn_SPC_CheckEventOk_specs_1;
extern asn_TYPE_member_t asn_MBR_CheckEventOk_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CheckEventOk_H_ */
#include <asn_internal.h>
