/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CheckProgressResponse_H_
#define	_CheckProgressResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CheckProgressOk.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CheckProgressResponse_PR {
	CheckProgressResponse_PR_NOTHING,	/* No components present */
	CheckProgressResponse_PR_checkProgressOk,
	CheckProgressResponse_PR_checkProgressError
	/* Extensions may appear below */
	
} CheckProgressResponse_PR;
typedef enum CheckProgressResponse__checkProgressError {
	CheckProgressResponse__checkProgressError_unknowndcSessionId	= 4,
	CheckProgressResponse__checkProgressError_invalidInputData	= 124,
	CheckProgressResponse__checkProgressError_missingInputData	= 125,
	CheckProgressResponse__checkProgressError_functionProviderBusy	= 126,
	CheckProgressResponse__checkProgressError_undefinedError	= 127
} e_CheckProgressResponse__checkProgressError;

/* CheckProgressResponse */
typedef struct CheckProgressResponse {
	CheckProgressResponse_PR present;
	union CheckProgressResponse_u {
		CheckProgressOk_t	 checkProgressOk;
		long	 checkProgressError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CheckProgressResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CheckProgressResponse;
extern asn_CHOICE_specifics_t asn_SPC_CheckProgressResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_CheckProgressResponse_1[2];
extern asn_per_constraints_t asn_PER_type_CheckProgressResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CheckProgressResponse_H_ */
#include <asn_internal.h>
