/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CompactSuccessResult.h"

static int
memb_compactAid_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_compactAid_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	2	/* (SIZE(2..2)) */};
static asn_per_constraints_t asn_PER_memb_compactAid_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  2,  2 }	/* (SIZE(2..2)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_CompactSuccessResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CompactSuccessResult, compactAid),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_compactAid_constr_2, &asn_PER_memb_compactAid_constr_2,  memb_compactAid_constraint_1 },
		0, 0, /* No default value */
		"compactAid"
		},
	{ ATF_POINTER, 1, offsetof(struct CompactSuccessResult, simaResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simaResponse"
		},
};
static const int asn_MAP_CompactSuccessResult_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_CompactSuccessResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CompactSuccessResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* simaResponse */
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 0, 0, 0 } /* compactAid */
};
asn_SEQUENCE_specifics_t asn_SPC_CompactSuccessResult_specs_1 = {
	sizeof(struct CompactSuccessResult),
	offsetof(struct CompactSuccessResult, _asn_ctx),
	asn_MAP_CompactSuccessResult_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_CompactSuccessResult_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CompactSuccessResult = {
	"CompactSuccessResult",
	"CompactSuccessResult",
	&asn_OP_SEQUENCE,
	asn_DEF_CompactSuccessResult_tags_1,
	sizeof(asn_DEF_CompactSuccessResult_tags_1)
		/sizeof(asn_DEF_CompactSuccessResult_tags_1[0]), /* 1 */
	asn_DEF_CompactSuccessResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_CompactSuccessResult_tags_1)
		/sizeof(asn_DEF_CompactSuccessResult_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CompactSuccessResult_1,
	2,	/* Elements count */
	&asn_SPC_CompactSuccessResult_specs_1	/* Additional specs */
};

