/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfirmDeviceChangeOk_H_
#define	_ConfirmDeviceChangeOk_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SmdpSigned5.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfirmDeviceChangeOk */
typedef struct ConfirmDeviceChangeOk {
	TransactionId_t	 transactionId;
	SmdpSigned5_t	 smdpSigned5;
	OCTET_STRING_t	 smdpSignature5;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmDeviceChangeOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmDeviceChangeOk;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfirmDeviceChangeOk_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmDeviceChangeOk_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmDeviceChangeOk_H_ */
#include <asn_internal.h>
