/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfirmDeviceChangeRequest_H_
#define	_ConfirmDeviceChangeRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "PrepareDeviceChangeResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfirmDeviceChangeRequest */
typedef struct ConfirmDeviceChangeRequest {
	TransactionId_t	 transactionId;
	PrepareDeviceChangeResponse_t	 prepareDeviceChangeResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmDeviceChangeRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmDeviceChangeRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_ConfirmDeviceChangeRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmDeviceChangeRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmDeviceChangeRequest_H_ */
#include <asn_internal.h>
