/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ConfirmDeviceChangeRequest.h"

asn_TYPE_member_t asn_MBR_ConfirmDeviceChangeRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmDeviceChangeRequest, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmDeviceChangeRequest, prepareDeviceChangeResponse),
		(ASN_TAG_CLASS_CONTEXT | (77 << 2)),
		0,
		&asn_DEF_PrepareDeviceChangeResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"prepareDeviceChangeResponse"
		},
};
static const ber_tlv_tag_t asn_DEF_ConfirmDeviceChangeRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (76 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfirmDeviceChangeRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (77 << 2)), 1, 0, 0 } /* prepareDeviceChangeResponse */
};
asn_SEQUENCE_specifics_t asn_SPC_ConfirmDeviceChangeRequest_specs_1 = {
	sizeof(struct ConfirmDeviceChangeRequest),
	offsetof(struct ConfirmDeviceChangeRequest, _asn_ctx),
	asn_MAP_ConfirmDeviceChangeRequest_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmDeviceChangeRequest = {
	"ConfirmDeviceChangeRequest",
	"ConfirmDeviceChangeRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfirmDeviceChangeRequest_tags_1,
	sizeof(asn_DEF_ConfirmDeviceChangeRequest_tags_1)
		/sizeof(asn_DEF_ConfirmDeviceChangeRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_ConfirmDeviceChangeRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfirmDeviceChangeRequest_tags_1)
		/sizeof(asn_DEF_ConfirmDeviceChangeRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConfirmDeviceChangeRequest_1,
	2,	/* Elements count */
	&asn_SPC_ConfirmDeviceChangeRequest_specs_1	/* Additional specs */
};

