/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../asn/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfigureAutoEnableResult_H_
#define	_ConfigureAutoEnableResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfigureAutoEnableResult {
	ConfigureAutoEnableResult_ok	= 0,
	ConfigureAutoEnableResult_insufficientMemory	= 1,
	ConfigureAutoEnableResult_commandError	= 7,
	ConfigureAutoEnableResult_undefinedError	= 127
} e_ConfigureAutoEnableResult;

/* ConfigureAutoEnableResult */
typedef long	 ConfigureAutoEnableResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfigureAutoEnableResult;
asn_struct_free_f ConfigureAutoEnableResult_free;
asn_struct_print_f ConfigureAutoEnableResult_print;
asn_constr_check_f ConfigureAutoEnableResult_constraint;
ber_type_decoder_f ConfigureAutoEnableResult_decode_ber;
der_type_encoder_f ConfigureAutoEnableResult_encode_der;
xer_type_decoder_f ConfigureAutoEnableResult_decode_xer;
xer_type_encoder_f ConfigureAutoEnableResult_encode_xer;
oer_type_decoder_f ConfigureAutoEnableResult_decode_oer;
oer_type_encoder_f ConfigureAutoEnableResult_encode_oer;
per_type_decoder_f ConfigureAutoEnableResult_decode_uper;
per_type_encoder_f ConfigureAutoEnableResult_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfigureAutoEnableResult_H_ */
#include <asn_internal.h>
