/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ConfirmDeviceChangeOk.h"

asn_TYPE_member_t asn_MBR_ConfirmDeviceChangeOk_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmDeviceChangeOk, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmDeviceChangeOk, smdpSigned5),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConfirmDeviceChangeOk, smdpSignature5),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature5"
		},
};
static const ber_tlv_tag_t asn_DEF_ConfirmDeviceChangeOk_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfirmDeviceChangeOk_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* smdpSigned5 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 2, 0, 0 }, /* smdpSignature5 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* transactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_ConfirmDeviceChangeOk_specs_1 = {
	sizeof(struct ConfirmDeviceChangeOk),
	offsetof(struct ConfirmDeviceChangeOk, _asn_ctx),
	asn_MAP_ConfirmDeviceChangeOk_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfirmDeviceChangeOk = {
	"ConfirmDeviceChangeOk",
	"ConfirmDeviceChangeOk",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfirmDeviceChangeOk_tags_1,
	sizeof(asn_DEF_ConfirmDeviceChangeOk_tags_1)
		/sizeof(asn_DEF_ConfirmDeviceChangeOk_tags_1[0]), /* 1 */
	asn_DEF_ConfirmDeviceChangeOk_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfirmDeviceChangeOk_tags_1)
		/sizeof(asn_DEF_ConfirmDeviceChangeOk_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConfirmDeviceChangeOk_1,
	3,	/* Elements count */
	&asn_SPC_ConfirmDeviceChangeOk_specs_1	/* Additional specs */
};

