/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ConfirmDeviceChangeResponse_H_
#define	_ConfirmDeviceChangeResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ConfirmDeviceChangeOk.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConfirmDeviceChangeResponse_PR {
	ConfirmDeviceChangeResponse_PR_NOTHING,	/* No components present */
	ConfirmDeviceChangeResponse_PR_confirmDeviceChangeOk,
	ConfirmDeviceChangeResponse_PR_confirmDeviceChangeError
	/* Extensions may appear below */
	
} ConfirmDeviceChangeResponse_PR;
typedef enum ConfirmDeviceChangeResponse__confirmDeviceChangeError {
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_invalidTransactionId	= 1,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_euiccSignatureInvalid	= 2,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_confirmationCodeMissing	= 3,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_confirmationCodeRefused	= 4,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_confirmationCodeInvalidMatch	= 5,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_confirmationCodeRetriesExceeded	= 6,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_invalidInputData	= 124,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_missingInputData	= 125,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_functionProviderBusy	= 126,
	ConfirmDeviceChangeResponse__confirmDeviceChangeError_undefinedError	= 127
} e_ConfirmDeviceChangeResponse__confirmDeviceChangeError;

/* ConfirmDeviceChangeResponse */
typedef struct ConfirmDeviceChangeResponse {
	ConfirmDeviceChangeResponse_PR present;
	union ConfirmDeviceChangeResponse_u {
		ConfirmDeviceChangeOk_t	 confirmDeviceChangeOk;
		long	 confirmDeviceChangeError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConfirmDeviceChangeResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmDeviceChangeResponse;
extern asn_CHOICE_specifics_t asn_SPC_ConfirmDeviceChangeResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_ConfirmDeviceChangeResponse_1[2];
extern asn_per_constraints_t asn_PER_type_ConfirmDeviceChangeResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmDeviceChangeResponse_H_ */
#include <asn_internal.h>
