/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ContactPcmpResponse_H_
#define	_ContactPcmpResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ContactPcmpResponse_PR {
	ContactPcmpResponse_PR_NOTHING,	/* No components present */
	ContactPcmpResponse_PR_contactPcmpResponseOk,
	ContactPcmpResponse_PR_contactPcmpResponseError
	/* Extensions may appear below */
	
} ContactPcmpResponse_PR;
typedef enum ContactPcmpResponse__contactPcmpResponseError {
	ContactPcmpResponse__contactPcmpResponseError_profileNotEnabled	= 2,
	ContactPcmpResponse__contactPcmpResponseError_commandError	= 7,
	ContactPcmpResponse__contactPcmpResponseError_noLprConfiguration	= 13,
	ContactPcmpResponse__contactPcmpResponseError_undefinedError	= 127
} e_ContactPcmpResponse__contactPcmpResponseError;

/* ContactPcmpResponse */
typedef struct ContactPcmpResponse {
	ContactPcmpResponse_PR present;
	union ContactPcmpResponse_u {
		struct ContactPcmpResponse__contactPcmpResponseOk {
			UTF8String_t	 pcmpAddress;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} contactPcmpResponseOk;
		long	 contactPcmpResponseError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ContactPcmpResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ContactPcmpResponse;
extern asn_CHOICE_specifics_t asn_SPC_ContactPcmpResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_ContactPcmpResponse_1[2];
extern asn_per_constraints_t asn_PER_type_ContactPcmpResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ContactPcmpResponse_H_ */
#include <asn_internal.h>
