/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ContactPcmpResponse.h"

static asn_oer_constraints_t asn_OER_type_ContactPcmpResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ContactPcmpResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_contactPcmpResponseOk_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ContactPcmpResponse__contactPcmpResponseOk, pcmpAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pcmpAddress"
		},
};
static const ber_tlv_tag_t asn_DEF_contactPcmpResponseOk_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_contactPcmpResponseOk_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* pcmpAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_contactPcmpResponseOk_specs_2 = {
	sizeof(struct ContactPcmpResponse__contactPcmpResponseOk),
	offsetof(struct ContactPcmpResponse__contactPcmpResponseOk, _asn_ctx),
	asn_MAP_contactPcmpResponseOk_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_contactPcmpResponseOk_2 = {
	"contactPcmpResponseOk",
	"contactPcmpResponseOk",
	&asn_OP_SEQUENCE,
	asn_DEF_contactPcmpResponseOk_tags_2,
	sizeof(asn_DEF_contactPcmpResponseOk_tags_2)
		/sizeof(asn_DEF_contactPcmpResponseOk_tags_2[0]) - 1, /* 1 */
	asn_DEF_contactPcmpResponseOk_tags_2,	/* Same as above */
	sizeof(asn_DEF_contactPcmpResponseOk_tags_2)
		/sizeof(asn_DEF_contactPcmpResponseOk_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_contactPcmpResponseOk_2,
	1,	/* Elements count */
	&asn_SPC_contactPcmpResponseOk_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ContactPcmpResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ContactPcmpResponse, choice.contactPcmpResponseOk),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_contactPcmpResponseOk_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactPcmpResponseOk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ContactPcmpResponse, choice.contactPcmpResponseError),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactPcmpResponseError"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ContactPcmpResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* contactPcmpResponseOk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* contactPcmpResponseError */
};
asn_CHOICE_specifics_t asn_SPC_ContactPcmpResponse_specs_1 = {
	sizeof(struct ContactPcmpResponse),
	offsetof(struct ContactPcmpResponse, _asn_ctx),
	offsetof(struct ContactPcmpResponse, present),
	sizeof(((struct ContactPcmpResponse *)0)->present),
	asn_MAP_ContactPcmpResponse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ContactPcmpResponse = {
	"ContactPcmpResponse",
	"ContactPcmpResponse",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ContactPcmpResponse_constr_1, &asn_PER_type_ContactPcmpResponse_constr_1, CHOICE_constraint },
	asn_MBR_ContactPcmpResponse_1,
	2,	/* Elements count */
	&asn_SPC_ContactPcmpResponse_specs_1	/* Additional specs */
};

