/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CtxParamsForDeviceChange_H_
#define	_CtxParamsForDeviceChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Iccid.h"
#include "DeviceInfo.h"
#include "Octet16.h"
#include "Octet4.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VendorSpecificExtension;

/* CtxParamsForDeviceChange */
typedef struct CtxParamsForDeviceChange {
	Iccid_t	 iccid;
	DeviceInfo_t	 deviceInfo;
	Octet16_t	*targetEidValue	/* OPTIONAL */;
	Octet4_t	*targetTacValue	/* OPTIONAL */;
	struct VendorSpecificExtension	*vendorSpecificExtension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CtxParamsForDeviceChange_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtxParamsForDeviceChange;
extern asn_SEQUENCE_specifics_t asn_SPC_CtxParamsForDeviceChange_specs_1;
extern asn_TYPE_member_t asn_MBR_CtxParamsForDeviceChange_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VendorSpecificExtension.h"

#endif	/* _CtxParamsForDeviceChange_H_ */
#include <asn_internal.h>
