/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_CtxParamsForProfileRecovery_H_
#define	_CtxParamsForProfileRecovery_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Iccid.h"
#include "DeviceInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VendorSpecificExtension;

/* CtxParamsForProfileRecovery */
typedef struct CtxParamsForProfileRecovery {
	Iccid_t	 iccid;
	DeviceInfo_t	 deviceInfo;
	struct VendorSpecificExtension	*vendorSpecificExtension	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CtxParamsForProfileRecovery_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CtxParamsForProfileRecovery;
extern asn_SEQUENCE_specifics_t asn_SPC_CtxParamsForProfileRecovery_specs_1;
extern asn_TYPE_member_t asn_MBR_CtxParamsForProfileRecovery_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VendorSpecificExtension.h"

#endif	/* _CtxParamsForProfileRecovery_H_ */
#include <asn_internal.h>
