/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "CtxParamsForDeviceChange.h"

asn_TYPE_member_t asn_MBR_CtxParamsForDeviceChange_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CtxParamsForDeviceChange, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CtxParamsForDeviceChange, deviceInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeviceInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deviceInfo"
		},
	{ ATF_POINTER, 3, offsetof(struct CtxParamsForDeviceChange, targetEidValue),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetEidValue"
		},
	{ ATF_POINTER, 2, offsetof(struct CtxParamsForDeviceChange, targetTacValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetTacValue"
		},
	{ ATF_POINTER, 1, offsetof(struct CtxParamsForDeviceChange, vendorSpecificExtension),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"vendorSpecificExtension"
		},
};
static const int asn_MAP_CtxParamsForDeviceChange_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_CtxParamsForDeviceChange_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CtxParamsForDeviceChange_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 1 }, /* iccid */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 2, -1, 0 }, /* targetEidValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* deviceInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* targetTacValue */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 } /* vendorSpecificExtension */
};
asn_SEQUENCE_specifics_t asn_SPC_CtxParamsForDeviceChange_specs_1 = {
	sizeof(struct CtxParamsForDeviceChange),
	offsetof(struct CtxParamsForDeviceChange, _asn_ctx),
	asn_MAP_CtxParamsForDeviceChange_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_CtxParamsForDeviceChange_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CtxParamsForDeviceChange = {
	"CtxParamsForDeviceChange",
	"CtxParamsForDeviceChange",
	&asn_OP_SEQUENCE,
	asn_DEF_CtxParamsForDeviceChange_tags_1,
	sizeof(asn_DEF_CtxParamsForDeviceChange_tags_1)
		/sizeof(asn_DEF_CtxParamsForDeviceChange_tags_1[0]), /* 1 */
	asn_DEF_CtxParamsForDeviceChange_tags_1,	/* Same as above */
	sizeof(asn_DEF_CtxParamsForDeviceChange_tags_1)
		/sizeof(asn_DEF_CtxParamsForDeviceChange_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CtxParamsForDeviceChange_1,
	5,	/* Elements count */
	&asn_SPC_CtxParamsForDeviceChange_specs_1	/* Additional specs */
};

