/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DeviceChangeData_H_
#define	_DeviceChangeData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Iccid.h"
#include <UTF8String.h>
#include <NULL.h>
#include <GeneralizedTime.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DeviceChangeData */
typedef struct DeviceChangeData {
	Iccid_t	 iccid;
	UTF8String_t	 activationCodeForDc;
	NULL_t	*deleteOldProfile	/* OPTIONAL */;
	NULL_t	*deleteNotificationForDcSupport	/* OPTIONAL */;
	UTF8String_t	*notificationAddress	/* OPTIONAL */;
	NULL_t	*profileRecoverySupport	/* OPTIONAL */;
	GeneralizedTime_t	*profileRecoveryValidityPeriod	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeviceChangeData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeviceChangeData;
extern asn_SEQUENCE_specifics_t asn_SPC_DeviceChangeData_specs_1;
extern asn_TYPE_member_t asn_MBR_DeviceChangeData_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _DeviceChangeData_H_ */
#include <asn_internal.h>
