/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "DeviceChangeConfiguration.h"

static int
memb_activationCodeForDc_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_activationCodeForDc_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_activationCodeForDc_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_DeviceChangeConfiguration_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_DeviceChangeConfiguration_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_requestToDp_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeConfiguration__requestToDp, smdpAddressForDc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpAddressForDc"
		},
	{ ATF_POINTER, 3, offsetof(struct DeviceChangeConfiguration__requestToDp, allowedCiPKId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allowedCiPKId"
		},
	{ ATF_POINTER, 2, offsetof(struct DeviceChangeConfiguration__requestToDp, eidRequired),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eidRequired"
		},
	{ ATF_POINTER, 1, offsetof(struct DeviceChangeConfiguration__requestToDp, tacRequired),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tacRequired"
		},
};
static const int asn_MAP_requestToDp_oms_2[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_requestToDp_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_requestToDp_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* smdpAddressForDc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* allowedCiPKId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eidRequired */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* tacRequired */
};
static asn_SEQUENCE_specifics_t asn_SPC_requestToDp_specs_2 = {
	sizeof(struct DeviceChangeConfiguration__requestToDp),
	offsetof(struct DeviceChangeConfiguration__requestToDp, _asn_ctx),
	asn_MAP_requestToDp_tag2el_2,
	4,	/* Count of tags in the map */
	asn_MAP_requestToDp_oms_2,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requestToDp_2 = {
	"requestToDp",
	"requestToDp",
	&asn_OP_SEQUENCE,
	asn_DEF_requestToDp_tags_2,
	sizeof(asn_DEF_requestToDp_tags_2)
		/sizeof(asn_DEF_requestToDp_tags_2[0]) - 1, /* 1 */
	asn_DEF_requestToDp_tags_2,	/* Same as above */
	sizeof(asn_DEF_requestToDp_tags_2)
		/sizeof(asn_DEF_requestToDp_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_requestToDp_2,
	4,	/* Elements count */
	&asn_SPC_requestToDp_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_usingStoredAc_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeConfiguration__usingStoredAc, activationCodeForDc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_activationCodeForDc_constr_9, &asn_PER_memb_activationCodeForDc_constr_9,  memb_activationCodeForDc_constraint_8 },
		0, 0, /* No default value */
		"activationCodeForDc"
		},
	{ ATF_POINTER, 1, offsetof(struct DeviceChangeConfiguration__usingStoredAc, deleteOldProfile),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteOldProfile"
		},
};
static const int asn_MAP_usingStoredAc_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_usingStoredAc_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_usingStoredAc_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* activationCodeForDc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* deleteOldProfile */
};
static asn_SEQUENCE_specifics_t asn_SPC_usingStoredAc_specs_8 = {
	sizeof(struct DeviceChangeConfiguration__usingStoredAc),
	offsetof(struct DeviceChangeConfiguration__usingStoredAc, _asn_ctx),
	asn_MAP_usingStoredAc_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_usingStoredAc_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_usingStoredAc_8 = {
	"usingStoredAc",
	"usingStoredAc",
	&asn_OP_SEQUENCE,
	asn_DEF_usingStoredAc_tags_8,
	sizeof(asn_DEF_usingStoredAc_tags_8)
		/sizeof(asn_DEF_usingStoredAc_tags_8[0]) - 1, /* 1 */
	asn_DEF_usingStoredAc_tags_8,	/* Same as above */
	sizeof(asn_DEF_usingStoredAc_tags_8)
		/sizeof(asn_DEF_usingStoredAc_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_usingStoredAc_8,
	2,	/* Elements count */
	&asn_SPC_usingStoredAc_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DeviceChangeConfiguration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeConfiguration, choice.requestToDp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_requestToDp_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestToDp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeConfiguration, choice.usingStoredAc),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_usingStoredAc_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"usingStoredAc"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_DeviceChangeConfiguration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* requestToDp */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* usingStoredAc */
};
asn_CHOICE_specifics_t asn_SPC_DeviceChangeConfiguration_specs_1 = {
	sizeof(struct DeviceChangeConfiguration),
	offsetof(struct DeviceChangeConfiguration, _asn_ctx),
	offsetof(struct DeviceChangeConfiguration, present),
	sizeof(((struct DeviceChangeConfiguration *)0)->present),
	asn_MAP_DeviceChangeConfiguration_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DeviceChangeConfiguration = {
	"DeviceChangeConfiguration",
	"DeviceChangeConfiguration",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_DeviceChangeConfiguration_constr_1, &asn_PER_type_DeviceChangeConfiguration_constr_1, CHOICE_constraint },
	asn_MBR_DeviceChangeConfiguration_1,
	2,	/* Elements count */
	&asn_SPC_DeviceChangeConfiguration_specs_1	/* Additional specs */
};

