/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DeviceChangeConfiguration_H_
#define	_DeviceChangeConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "SubjectKeyIdentifier.h"
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeviceChangeConfiguration_PR {
	DeviceChangeConfiguration_PR_NOTHING,	/* No components present */
	DeviceChangeConfiguration_PR_requestToDp,
	DeviceChangeConfiguration_PR_usingStoredAc
	/* Extensions may appear below */
	
} DeviceChangeConfiguration_PR;

/* DeviceChangeConfiguration */
typedef struct DeviceChangeConfiguration {
	DeviceChangeConfiguration_PR present;
	union DeviceChangeConfiguration_u {
		struct DeviceChangeConfiguration__requestToDp {
			UTF8String_t	 smdpAddressForDc;
			SubjectKeyIdentifier_t	*allowedCiPKId	/* OPTIONAL */;
			NULL_t	*eidRequired	/* OPTIONAL */;
			NULL_t	*tacRequired	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} requestToDp;
		struct DeviceChangeConfiguration__usingStoredAc {
			UTF8String_t	 activationCodeForDc;
			NULL_t	*deleteOldProfile	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} usingStoredAc;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeviceChangeConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeviceChangeConfiguration;
extern asn_CHOICE_specifics_t asn_SPC_DeviceChangeConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_DeviceChangeConfiguration_1[2];
extern asn_per_constraints_t asn_PER_type_DeviceChangeConfiguration_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DeviceChangeConfiguration_H_ */
#include <asn_internal.h>
