/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "DeviceChangeData.h"

static int
memb_activationCodeForDc_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_activationCodeForDc_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_activationCodeForDc_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_DeviceChangeData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeData, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DeviceChangeData, activationCodeForDc),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_activationCodeForDc_constr_3, &asn_PER_memb_activationCodeForDc_constr_3,  memb_activationCodeForDc_constraint_1 },
		0, 0, /* No default value */
		"activationCodeForDc"
		},
	{ ATF_POINTER, 5, offsetof(struct DeviceChangeData, deleteOldProfile),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteOldProfile"
		},
	{ ATF_POINTER, 4, offsetof(struct DeviceChangeData, deleteNotificationForDcSupport),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteNotificationForDcSupport"
		},
	{ ATF_POINTER, 3, offsetof(struct DeviceChangeData, notificationAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationAddress"
		},
	{ ATF_POINTER, 2, offsetof(struct DeviceChangeData, profileRecoverySupport),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileRecoverySupport"
		},
	{ ATF_POINTER, 1, offsetof(struct DeviceChangeData, profileRecoveryValidityPeriod),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileRecoveryValidityPeriod"
		},
};
static const int asn_MAP_DeviceChangeData_oms_1[] = { 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_DeviceChangeData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DeviceChangeData_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* activationCodeForDc */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* deleteOldProfile */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* deleteNotificationForDcSupport */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 }, /* notificationAddress */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 5, 0, 0 }, /* profileRecoverySupport */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 6, 0, 0 } /* profileRecoveryValidityPeriod */
};
asn_SEQUENCE_specifics_t asn_SPC_DeviceChangeData_specs_1 = {
	sizeof(struct DeviceChangeData),
	offsetof(struct DeviceChangeData, _asn_ctx),
	asn_MAP_DeviceChangeData_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_DeviceChangeData_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DeviceChangeData = {
	"DeviceChangeData",
	"DeviceChangeData",
	&asn_OP_SEQUENCE,
	asn_DEF_DeviceChangeData_tags_1,
	sizeof(asn_DEF_DeviceChangeData_tags_1)
		/sizeof(asn_DEF_DeviceChangeData_tags_1[0]), /* 1 */
	asn_DEF_DeviceChangeData_tags_1,	/* Same as above */
	sizeof(asn_DEF_DeviceChangeData_tags_1)
		/sizeof(asn_DEF_DeviceChangeData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DeviceChangeData_1,
	7,	/* Elements count */
	&asn_SPC_DeviceChangeData_specs_1	/* Additional specs */
};

