/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_DeviceChangeResponse_H_
#define	_DeviceChangeResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DeviceChangeData.h"
#include "EncryptedDeviceChangeData.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeviceChangeResponse_PR {
	DeviceChangeResponse_PR_NOTHING,	/* No components present */
	DeviceChangeResponse_PR_deviceChangeData,
	DeviceChangeResponse_PR_encryptedDeviceChangeData
	/* Extensions may appear below */
	
} DeviceChangeResponse_PR;

/* DeviceChangeResponse */
typedef struct DeviceChangeResponse {
	DeviceChangeResponse_PR present;
	union DeviceChangeResponse_u {
		DeviceChangeData_t	 deviceChangeData;
		EncryptedDeviceChangeData_t	 encryptedDeviceChangeData;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeviceChangeResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeviceChangeResponse;
extern asn_CHOICE_specifics_t asn_SPC_DeviceChangeResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_DeviceChangeResponse_1[2];
extern asn_per_constraints_t asn_PER_type_DeviceChangeResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DeviceChangeResponse_H_ */
#include <asn_internal.h>
