/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_E4EResultCode_H_
#define	_E4EResultCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E4EResultCode {
	E4EResultCode_success	= 0,
	E4EResultCode_errorBusy	= 1,
	E4EResultCode_errorComm	= 2,
	E4EResultCode_errorAuth	= 3,
	E4EResultCode_errorNoProfile	= 4,
	E4EResultCode_errorEligibility	= 5,
	E4EResultCode_errorInstall	= 6,
	E4EResultCode_errorPin	= 7,
	E4EResultCode_errorProfileRef	= 8,
	E4EResultCode_errorAlreadyEnabled	= 9,
	E4EResultCode_errorAlreadyDisabled	= 10,
	E4EResultCode_errorConfirmationCode	= 11,
	E4EResultCode_errorRpmDisabled	= 12,
	E4EResultCode_errorProfileDoesNotExist	= 13,
	E4EResultCode_undefinedError	= 127
} e_E4EResultCode;

/* E4EResultCode */
typedef long	 E4EResultCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E4EResultCode;
asn_struct_free_f E4EResultCode_free;
asn_struct_print_f E4EResultCode_print;
asn_constr_check_f E4EResultCode_constraint;
ber_type_decoder_f E4EResultCode_decode_ber;
der_type_encoder_f E4EResultCode_encode_der;
xer_type_decoder_f E4EResultCode_decode_xer;
xer_type_encoder_f E4EResultCode_encode_xer;
oer_type_decoder_f E4EResultCode_decode_oer;
oer_type_encoder_f E4EResultCode_encode_oer;
per_type_decoder_f E4EResultCode_decode_uper;
per_type_encoder_f E4EResultCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E4EResultCode_H_ */
#include <asn_internal.h>
