/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_E4EResponse_H_
#define	_E4EResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E4EResultCode.h"
#include <UTF8String.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include "Iccid.h"
#include "ProfileState.h"
#include <constr_SEQUENCE_OF.h>
#include "RpmPackage.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E4EResponse__resultData_PR {
	E4EResponse__resultData_PR_NOTHING,	/* No components present */
	E4EResponse__resultData_PR_startDownloadResponse,
	E4EResponse__resultData_PR_listProfilesResponse,
	E4EResponse__resultData_PR_pollRpmPackageResponse,
	E4EResponse__resultData_PR_confirmDownloadResponse
	/* Extensions may appear below */
	
} E4EResponse__resultData_PR;

/* Forward definitions */
typedef struct E4EResponse__resultData__listProfilesResponse__Member {
	Iccid_t	 iccid;
	ProfileState_t	 profileState;
	UTF8String_t	 serviceProviderName;
	UTF8String_t	 profileName;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E4EResponse__resultData__listProfilesResponse__Member;

/* E4EResponse */
typedef struct E4EResponse {
	E4EResultCode_t	 resultCode;
	struct E4EResponse__resultData {
		E4EResponse__resultData_PR present;
		union E4EResponse__resultData_u {
			struct E4EResponse__resultData__startDownloadResponse {
				UTF8String_t	 serviceProviderName;
				UTF8String_t	 profileName;
				NULL_t	*ccRequired	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} startDownloadResponse;
			struct E4EResponse__resultData__listProfilesResponse {
				A_SEQUENCE_OF(E4EResponse__resultData__listProfilesResponse__Member) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} listProfilesResponse;
			struct E4EResponse__resultData__pollRpmPackageResponse {
				RpmPackage_t	 rpmPackage;
				NULL_t	*rpmPending	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} pollRpmPackageResponse;
			struct E4EResponse__resultData__confirmDownloadResponse {
				Iccid_t	 iccid;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} confirmDownloadResponse;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *resultData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E4EResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E4EResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _E4EResponse_H_ */
#include <asn_internal.h>
