/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "E4EResponse.h"

static int
memb_serviceProviderName_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_serviceProviderName_constraint_10(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_10(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_profileName_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileName_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_profileName_constr_14 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_profileName_constr_14 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_resultData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_resultData_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_startDownloadResponse_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__startDownloadResponse, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_5, &asn_PER_memb_serviceProviderName_constr_5,  memb_serviceProviderName_constraint_4 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__startDownloadResponse, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileName_constr_6, &asn_PER_memb_profileName_constr_6,  memb_profileName_constraint_4 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 1, offsetof(struct E4EResponse__resultData__startDownloadResponse, ccRequired),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ccRequired"
		},
};
static const int asn_MAP_startDownloadResponse_oms_4[] = { 2 };
static const ber_tlv_tag_t asn_DEF_startDownloadResponse_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_startDownloadResponse_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* ccRequired */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 0, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 } /* profileName */
};
static asn_SEQUENCE_specifics_t asn_SPC_startDownloadResponse_specs_4 = {
	sizeof(struct E4EResponse__resultData__startDownloadResponse),
	offsetof(struct E4EResponse__resultData__startDownloadResponse, _asn_ctx),
	asn_MAP_startDownloadResponse_tag2el_4,
	3,	/* Count of tags in the map */
	asn_MAP_startDownloadResponse_oms_4,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_startDownloadResponse_4 = {
	"startDownloadResponse",
	"startDownloadResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_startDownloadResponse_tags_4,
	sizeof(asn_DEF_startDownloadResponse_tags_4)
		/sizeof(asn_DEF_startDownloadResponse_tags_4[0]) - 1, /* 1 */
	asn_DEF_startDownloadResponse_tags_4,	/* Same as above */
	sizeof(asn_DEF_startDownloadResponse_tags_4)
		/sizeof(asn_DEF_startDownloadResponse_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_startDownloadResponse_4,
	3,	/* Elements count */
	&asn_SPC_startDownloadResponse_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__listProfilesResponse__Member, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__listProfilesResponse__Member, profileState),
		(ASN_TAG_CLASS_CONTEXT | (112 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileState"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__listProfilesResponse__Member, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_13, &asn_PER_memb_serviceProviderName_constr_13,  memb_serviceProviderName_constraint_10 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__listProfilesResponse__Member, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_profileName_constr_14, &asn_PER_memb_profileName_constr_14,  memb_profileName_constraint_10 },
		0, 0, /* No default value */
		"profileName"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_10[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 2, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 3, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (112 << 2)), 1, 0, 0 } /* profileState */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_10 = {
	sizeof(struct E4EResponse__resultData__listProfilesResponse__Member),
	offsetof(struct E4EResponse__resultData__listProfilesResponse__Member, _asn_ctx),
	asn_MAP_Member_tag2el_10,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_10 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_10,
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	asn_DEF_Member_tags_10,	/* Same as above */
	sizeof(asn_DEF_Member_tags_10)
		/sizeof(asn_DEF_Member_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_10,
	4,	/* Elements count */
	&asn_SPC_Member_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_listProfilesResponse_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_listProfilesResponse_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listProfilesResponse_specs_9 = {
	sizeof(struct E4EResponse__resultData__listProfilesResponse),
	offsetof(struct E4EResponse__resultData__listProfilesResponse, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listProfilesResponse_9 = {
	"listProfilesResponse",
	"listProfilesResponse",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_listProfilesResponse_tags_9,
	sizeof(asn_DEF_listProfilesResponse_tags_9)
		/sizeof(asn_DEF_listProfilesResponse_tags_9[0]) - 1, /* 1 */
	asn_DEF_listProfilesResponse_tags_9,	/* Same as above */
	sizeof(asn_DEF_listProfilesResponse_tags_9)
		/sizeof(asn_DEF_listProfilesResponse_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_listProfilesResponse_9,
	1,	/* Single element */
	&asn_SPC_listProfilesResponse_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pollRpmPackageResponse_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__pollRpmPackageResponse, rpmPackage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RpmPackage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmPackage"
		},
	{ ATF_POINTER, 1, offsetof(struct E4EResponse__resultData__pollRpmPackageResponse, rpmPending),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmPending"
		},
};
static const int asn_MAP_pollRpmPackageResponse_oms_16[] = { 1 };
static const ber_tlv_tag_t asn_DEF_pollRpmPackageResponse_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_pollRpmPackageResponse_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rpmPackage */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rpmPending */
};
static asn_SEQUENCE_specifics_t asn_SPC_pollRpmPackageResponse_specs_16 = {
	sizeof(struct E4EResponse__resultData__pollRpmPackageResponse),
	offsetof(struct E4EResponse__resultData__pollRpmPackageResponse, _asn_ctx),
	asn_MAP_pollRpmPackageResponse_tag2el_16,
	2,	/* Count of tags in the map */
	asn_MAP_pollRpmPackageResponse_oms_16,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pollRpmPackageResponse_16 = {
	"pollRpmPackageResponse",
	"pollRpmPackageResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_pollRpmPackageResponse_tags_16,
	sizeof(asn_DEF_pollRpmPackageResponse_tags_16)
		/sizeof(asn_DEF_pollRpmPackageResponse_tags_16[0]) - 1, /* 1 */
	asn_DEF_pollRpmPackageResponse_tags_16,	/* Same as above */
	sizeof(asn_DEF_pollRpmPackageResponse_tags_16)
		/sizeof(asn_DEF_pollRpmPackageResponse_tags_16[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_pollRpmPackageResponse_16,
	2,	/* Elements count */
	&asn_SPC_pollRpmPackageResponse_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_confirmDownloadResponse_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData__confirmDownloadResponse, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_confirmDownloadResponse_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_confirmDownloadResponse_tag2el_20[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_confirmDownloadResponse_specs_20 = {
	sizeof(struct E4EResponse__resultData__confirmDownloadResponse),
	offsetof(struct E4EResponse__resultData__confirmDownloadResponse, _asn_ctx),
	asn_MAP_confirmDownloadResponse_tag2el_20,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_confirmDownloadResponse_20 = {
	"confirmDownloadResponse",
	"confirmDownloadResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_confirmDownloadResponse_tags_20,
	sizeof(asn_DEF_confirmDownloadResponse_tags_20)
		/sizeof(asn_DEF_confirmDownloadResponse_tags_20[0]) - 1, /* 1 */
	asn_DEF_confirmDownloadResponse_tags_20,	/* Same as above */
	sizeof(asn_DEF_confirmDownloadResponse_tags_20)
		/sizeof(asn_DEF_confirmDownloadResponse_tags_20[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_confirmDownloadResponse_20,
	1,	/* Elements count */
	&asn_SPC_confirmDownloadResponse_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_resultData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData, choice.startDownloadResponse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_startDownloadResponse_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"startDownloadResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData, choice.listProfilesResponse),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_listProfilesResponse_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listProfilesResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData, choice.pollRpmPackageResponse),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_pollRpmPackageResponse_16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pollRpmPackageResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse__resultData, choice.confirmDownloadResponse),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_confirmDownloadResponse_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmDownloadResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_resultData_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startDownloadResponse */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* listProfilesResponse */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 }, /* pollRpmPackageResponse */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 3, 0, 0 } /* confirmDownloadResponse */
};
static asn_CHOICE_specifics_t asn_SPC_resultData_specs_3 = {
	sizeof(struct E4EResponse__resultData),
	offsetof(struct E4EResponse__resultData, _asn_ctx),
	offsetof(struct E4EResponse__resultData, present),
	sizeof(((struct E4EResponse__resultData *)0)->present),
	asn_MAP_resultData_tag2el_3,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_resultData_3 = {
	"resultData",
	"resultData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_resultData_constr_3, &asn_PER_type_resultData_constr_3, CHOICE_constraint },
	asn_MBR_resultData_3,
	4,	/* Elements count */
	&asn_SPC_resultData_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_E4EResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4EResponse, resultCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E4EResultCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resultCode"
		},
	{ ATF_POINTER, 1, offsetof(struct E4EResponse, resultData),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_resultData_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resultData"
		},
};
static const int asn_MAP_E4EResponse_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_E4EResponse_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E4EResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* resultCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* resultData */
};
static asn_SEQUENCE_specifics_t asn_SPC_E4EResponse_specs_1 = {
	sizeof(struct E4EResponse),
	offsetof(struct E4EResponse, _asn_ctx),
	asn_MAP_E4EResponse_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_E4EResponse_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E4EResponse = {
	"E4EResponse",
	"E4EResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_E4EResponse_tags_1,
	sizeof(asn_DEF_E4EResponse_tags_1)
		/sizeof(asn_DEF_E4EResponse_tags_1[0]) - 1, /* 1 */
	asn_DEF_E4EResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_E4EResponse_tags_1)
		/sizeof(asn_DEF_E4EResponse_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E4EResponse_1,
	2,	/* Elements count */
	&asn_SPC_E4EResponse_specs_1	/* Additional specs */
};

