/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "E4ERequest.h"

static int
memb_activationCode_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pinCode_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 4 && size <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pinCode_constraint_17(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 4 && size <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pinCode_constraint_21(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 4 && size <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pinCode_constraint_29(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 4 && size <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_changeConfirmationPin_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size >= 9 && size <= 17)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_activationCode_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_activationCode_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pinCode_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_pinCode_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pinCode_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_pinCode_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pinCode_constr_22 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_pinCode_constr_22 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_pinCode_constr_30 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_pinCode_constr_30 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_changeConfirmationPin_constr_24 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_changeConfirmationPin_constr_24 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_E4ERequest_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_E4ERequest_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  11 }	/* (0..11,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_startDownload_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest__startDownload, activationCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_activationCode_constr_3, &asn_PER_memb_activationCode_constr_3,  memb_activationCode_constraint_2 },
		0, 0, /* No default value */
		"activationCode"
		},
};
static const ber_tlv_tag_t asn_DEF_startDownload_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_startDownload_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* activationCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_startDownload_specs_2 = {
	sizeof(struct E4ERequest__startDownload),
	offsetof(struct E4ERequest__startDownload, _asn_ctx),
	asn_MAP_startDownload_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_startDownload_2 = {
	"startDownload",
	"startDownload",
	&asn_OP_SEQUENCE,
	asn_DEF_startDownload_tags_2,
	sizeof(asn_DEF_startDownload_tags_2)
		/sizeof(asn_DEF_startDownload_tags_2[0]) - 1, /* 1 */
	asn_DEF_startDownload_tags_2,	/* Same as above */
	sizeof(asn_DEF_startDownload_tags_2)
		/sizeof(asn_DEF_startDownload_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_startDownload_2,
	1,	/* Elements count */
	&asn_SPC_startDownload_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_confirmDownload_5[] = {
	{ ATF_POINTER, 3, offsetof(struct E4ERequest__confirmDownload, enable),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enable"
		},
	{ ATF_POINTER, 2, offsetof(struct E4ERequest__confirmDownload, confirmationCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmationCode"
		},
	{ ATF_POINTER, 1, offsetof(struct E4ERequest__confirmDownload, pinCode),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_pinCode_constr_8, &asn_PER_memb_pinCode_constr_8,  memb_pinCode_constraint_5 },
		0, 0, /* No default value */
		"pinCode"
		},
};
static const int asn_MAP_confirmDownload_oms_5[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_confirmDownload_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_confirmDownload_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* enable */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* confirmationCode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* pinCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_confirmDownload_specs_5 = {
	sizeof(struct E4ERequest__confirmDownload),
	offsetof(struct E4ERequest__confirmDownload, _asn_ctx),
	asn_MAP_confirmDownload_tag2el_5,
	3,	/* Count of tags in the map */
	asn_MAP_confirmDownload_oms_5,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_confirmDownload_5 = {
	"confirmDownload",
	"confirmDownload",
	&asn_OP_SEQUENCE,
	asn_DEF_confirmDownload_tags_5,
	sizeof(asn_DEF_confirmDownload_tags_5)
		/sizeof(asn_DEF_confirmDownload_tags_5[0]) - 1, /* 1 */
	asn_DEF_confirmDownload_tags_5,	/* Same as above */
	sizeof(asn_DEF_confirmDownload_tags_5)
		/sizeof(asn_DEF_confirmDownload_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_confirmDownload_5,
	3,	/* Elements count */
	&asn_SPC_confirmDownload_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_enableProfile_11[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest__enableProfile, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_enableProfile_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_enableProfile_tag2el_11[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_enableProfile_specs_11 = {
	sizeof(struct E4ERequest__enableProfile),
	offsetof(struct E4ERequest__enableProfile, _asn_ctx),
	asn_MAP_enableProfile_tag2el_11,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_enableProfile_11 = {
	"enableProfile",
	"enableProfile",
	&asn_OP_SEQUENCE,
	asn_DEF_enableProfile_tags_11,
	sizeof(asn_DEF_enableProfile_tags_11)
		/sizeof(asn_DEF_enableProfile_tags_11[0]) - 1, /* 1 */
	asn_DEF_enableProfile_tags_11,	/* Same as above */
	sizeof(asn_DEF_enableProfile_tags_11)
		/sizeof(asn_DEF_enableProfile_tags_11[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_enableProfile_11,
	1,	/* Elements count */
	&asn_SPC_enableProfile_specs_11	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_disableProfile_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest__disableProfile, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_disableProfile_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_disableProfile_tag2el_14[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_disableProfile_specs_14 = {
	sizeof(struct E4ERequest__disableProfile),
	offsetof(struct E4ERequest__disableProfile, _asn_ctx),
	asn_MAP_disableProfile_tag2el_14,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_disableProfile_14 = {
	"disableProfile",
	"disableProfile",
	&asn_OP_SEQUENCE,
	asn_DEF_disableProfile_tags_14,
	sizeof(asn_DEF_disableProfile_tags_14)
		/sizeof(asn_DEF_disableProfile_tags_14[0]) - 1, /* 1 */
	asn_DEF_disableProfile_tags_14,	/* Same as above */
	sizeof(asn_DEF_disableProfile_tags_14)
		/sizeof(asn_DEF_disableProfile_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_disableProfile_14,
	1,	/* Elements count */
	&asn_SPC_disableProfile_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_deleteProfile_17[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest__deleteProfile, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_POINTER, 1, offsetof(struct E4ERequest__deleteProfile, pinCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_pinCode_constr_19, &asn_PER_memb_pinCode_constr_19,  memb_pinCode_constraint_17 },
		0, 0, /* No default value */
		"pinCode"
		},
};
static const int asn_MAP_deleteProfile_oms_17[] = { 1 };
static const ber_tlv_tag_t asn_DEF_deleteProfile_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_deleteProfile_tag2el_17[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pinCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_deleteProfile_specs_17 = {
	sizeof(struct E4ERequest__deleteProfile),
	offsetof(struct E4ERequest__deleteProfile, _asn_ctx),
	asn_MAP_deleteProfile_tag2el_17,
	2,	/* Count of tags in the map */
	asn_MAP_deleteProfile_oms_17,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_deleteProfile_17 = {
	"deleteProfile",
	"deleteProfile",
	&asn_OP_SEQUENCE,
	asn_DEF_deleteProfile_tags_17,
	sizeof(asn_DEF_deleteProfile_tags_17)
		/sizeof(asn_DEF_deleteProfile_tags_17[0]) - 1, /* 1 */
	asn_DEF_deleteProfile_tags_17,	/* Same as above */
	sizeof(asn_DEF_deleteProfile_tags_17)
		/sizeof(asn_DEF_deleteProfile_tags_17[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_deleteProfile_17,
	2,	/* Elements count */
	&asn_SPC_deleteProfile_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_euiccMemReset_21[] = {
	{ ATF_POINTER, 1, offsetof(struct E4ERequest__euiccMemReset, pinCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_pinCode_constr_22, &asn_PER_memb_pinCode_constr_22,  memb_pinCode_constraint_21 },
		0, 0, /* No default value */
		"pinCode"
		},
};
static const int asn_MAP_euiccMemReset_oms_21[] = { 0 };
static const ber_tlv_tag_t asn_DEF_euiccMemReset_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_euiccMemReset_tag2el_21[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* pinCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_euiccMemReset_specs_21 = {
	sizeof(struct E4ERequest__euiccMemReset),
	offsetof(struct E4ERequest__euiccMemReset, _asn_ctx),
	asn_MAP_euiccMemReset_tag2el_21,
	1,	/* Count of tags in the map */
	asn_MAP_euiccMemReset_oms_21,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_euiccMemReset_21 = {
	"euiccMemReset",
	"euiccMemReset",
	&asn_OP_SEQUENCE,
	asn_DEF_euiccMemReset_tags_21,
	sizeof(asn_DEF_euiccMemReset_tags_21)
		/sizeof(asn_DEF_euiccMemReset_tags_21[0]) - 1, /* 1 */
	asn_DEF_euiccMemReset_tags_21,	/* Same as above */
	sizeof(asn_DEF_euiccMemReset_tags_21)
		/sizeof(asn_DEF_euiccMemReset_tags_21[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_euiccMemReset_21,
	1,	/* Elements count */
	&asn_SPC_euiccMemReset_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pollRpmPackage_26[] = {
	{ ATF_POINTER, 1, offsetof(struct E4ERequest__pollRpmPackage, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const int asn_MAP_pollRpmPackage_oms_26[] = { 0 };
static const ber_tlv_tag_t asn_DEF_pollRpmPackage_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_pollRpmPackage_tag2el_26[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_pollRpmPackage_specs_26 = {
	sizeof(struct E4ERequest__pollRpmPackage),
	offsetof(struct E4ERequest__pollRpmPackage, _asn_ctx),
	asn_MAP_pollRpmPackage_tag2el_26,
	1,	/* Count of tags in the map */
	asn_MAP_pollRpmPackage_oms_26,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pollRpmPackage_26 = {
	"pollRpmPackage",
	"pollRpmPackage",
	&asn_OP_SEQUENCE,
	asn_DEF_pollRpmPackage_tags_26,
	sizeof(asn_DEF_pollRpmPackage_tags_26)
		/sizeof(asn_DEF_pollRpmPackage_tags_26[0]) - 1, /* 1 */
	asn_DEF_pollRpmPackage_tags_26,	/* Same as above */
	sizeof(asn_DEF_pollRpmPackage_tags_26)
		/sizeof(asn_DEF_pollRpmPackage_tags_26[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_pollRpmPackage_26,
	1,	/* Elements count */
	&asn_SPC_pollRpmPackage_specs_26	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_confirmRpmPackage_29[] = {
	{ ATF_POINTER, 1, offsetof(struct E4ERequest__confirmRpmPackage, pinCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_pinCode_constr_30, &asn_PER_memb_pinCode_constr_30,  memb_pinCode_constraint_29 },
		0, 0, /* No default value */
		"pinCode"
		},
};
static const int asn_MAP_confirmRpmPackage_oms_29[] = { 0 };
static const ber_tlv_tag_t asn_DEF_confirmRpmPackage_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_confirmRpmPackage_tag2el_29[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* pinCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_confirmRpmPackage_specs_29 = {
	sizeof(struct E4ERequest__confirmRpmPackage),
	offsetof(struct E4ERequest__confirmRpmPackage, _asn_ctx),
	asn_MAP_confirmRpmPackage_tag2el_29,
	1,	/* Count of tags in the map */
	asn_MAP_confirmRpmPackage_oms_29,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_confirmRpmPackage_29 = {
	"confirmRpmPackage",
	"confirmRpmPackage",
	&asn_OP_SEQUENCE,
	asn_DEF_confirmRpmPackage_tags_29,
	sizeof(asn_DEF_confirmRpmPackage_tags_29)
		/sizeof(asn_DEF_confirmRpmPackage_tags_29[0]) - 1, /* 1 */
	asn_DEF_confirmRpmPackage_tags_29,	/* Same as above */
	sizeof(asn_DEF_confirmRpmPackage_tags_29)
		/sizeof(asn_DEF_confirmRpmPackage_tags_29[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_confirmRpmPackage_29,
	1,	/* Elements count */
	&asn_SPC_confirmRpmPackage_specs_29	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_E4ERequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.startDownload),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_startDownload_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"startDownload"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.confirmDownload),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_confirmDownload_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmDownload"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.listProfiles),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listProfiles"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.enableProfile),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_enableProfile_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enableProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.disableProfile),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_disableProfile_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"disableProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.deleteProfile),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_deleteProfile_17,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteProfile"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.euiccMemReset),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_euiccMemReset_21,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccMemReset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.changeConfirmationPin),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_changeConfirmationPin_constr_24, &asn_PER_memb_changeConfirmationPin_constr_24,  memb_changeConfirmationPin_constraint_1 },
		0, 0, /* No default value */
		"changeConfirmationPin"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.setRpmAllow),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setRpmAllow"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.pollRpmPackage),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		0,
		&asn_DEF_pollRpmPackage_26,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pollRpmPackage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.confirmRpmPackage),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_confirmRpmPackage_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"confirmRpmPackage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E4ERequest, choice.cancelSession),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSession"
		},
};
static const ber_tlv_tag_t asn_DEF_E4ERequest_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (4 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E4ERequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startDownload */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* confirmDownload */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* listProfiles */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* enableProfile */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* disableProfile */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* deleteProfile */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* euiccMemReset */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* changeConfirmationPin */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* setRpmAllow */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* pollRpmPackage */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* confirmRpmPackage */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* cancelSession */
};
static asn_CHOICE_specifics_t asn_SPC_E4ERequest_specs_1 = {
	sizeof(struct E4ERequest),
	offsetof(struct E4ERequest, _asn_ctx),
	offsetof(struct E4ERequest, present),
	sizeof(((struct E4ERequest *)0)->present),
	asn_MAP_E4ERequest_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0,
	12	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_E4ERequest = {
	"E4ERequest",
	"E4ERequest",
	&asn_OP_CHOICE,
	asn_DEF_E4ERequest_tags_1,
	sizeof(asn_DEF_E4ERequest_tags_1)
		/sizeof(asn_DEF_E4ERequest_tags_1[0]), /* 1 */
	asn_DEF_E4ERequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_E4ERequest_tags_1)
		/sizeof(asn_DEF_E4ERequest_tags_1[0]), /* 1 */
	{ &asn_OER_type_E4ERequest_constr_1, &asn_PER_type_E4ERequest_constr_1, CHOICE_constraint },
	asn_MBR_E4ERequest_1,
	12,	/* Elements count */
	&asn_SPC_E4ERequest_specs_1	/* Additional specs */
};

