/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_E4ERequest_H_
#define	_E4ERequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <UTF8String.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>
#include "Iccid.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E4ERequest_PR {
	E4ERequest_PR_NOTHING,	/* No components present */
	E4ERequest_PR_startDownload,
	E4ERequest_PR_confirmDownload,
	E4ERequest_PR_listProfiles,
	E4ERequest_PR_enableProfile,
	E4ERequest_PR_disableProfile,
	E4ERequest_PR_deleteProfile,
	E4ERequest_PR_euiccMemReset,
	E4ERequest_PR_changeConfirmationPin,
	E4ERequest_PR_setRpmAllow,
	E4ERequest_PR_pollRpmPackage,
	E4ERequest_PR_confirmRpmPackage,
	E4ERequest_PR_cancelSession
	/* Extensions may appear below */
	
} E4ERequest_PR;

/* E4ERequest */
typedef struct E4ERequest {
	E4ERequest_PR present;
	union E4ERequest_u {
		struct E4ERequest__startDownload {
			UTF8String_t	 activationCode;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} startDownload;
		struct E4ERequest__confirmDownload {
			NULL_t	*enable	/* OPTIONAL */;
			UTF8String_t	*confirmationCode	/* OPTIONAL */;
			UTF8String_t	*pinCode	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} confirmDownload;
		NULL_t	 listProfiles;
		struct E4ERequest__enableProfile {
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} enableProfile;
		struct E4ERequest__disableProfile {
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} disableProfile;
		struct E4ERequest__deleteProfile {
			Iccid_t	 iccid;
			UTF8String_t	*pinCode	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} deleteProfile;
		struct E4ERequest__euiccMemReset {
			UTF8String_t	*pinCode	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} euiccMemReset;
		UTF8String_t	 changeConfirmationPin;
		BOOLEAN_t	 setRpmAllow;
		struct E4ERequest__pollRpmPackage {
			Iccid_t	*iccid	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} pollRpmPackage;
		struct E4ERequest__confirmRpmPackage {
			UTF8String_t	*pinCode	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} confirmRpmPackage;
		NULL_t	 cancelSession;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E4ERequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E4ERequest;

#ifdef __cplusplus
}
#endif

#endif	/* _E4ERequest_H_ */
#include <asn_internal.h>
