/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EncryptedDeviceChangeData.h"

static asn_TYPE_member_t asn_MBR_sequenceOf87_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_sequenceOf87_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_sequenceOf87_specs_4 = {
	sizeof(struct EncryptedDeviceChangeData__sequenceOf87),
	offsetof(struct EncryptedDeviceChangeData__sequenceOf87, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sequenceOf87_4 = {
	"sequenceOf87",
	"sequenceOf87",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_sequenceOf87_tags_4,
	sizeof(asn_DEF_sequenceOf87_tags_4)
		/sizeof(asn_DEF_sequenceOf87_tags_4[0]) - 1, /* 1 */
	asn_DEF_sequenceOf87_tags_4,	/* Same as above */
	sizeof(asn_DEF_sequenceOf87_tags_4)
		/sizeof(asn_DEF_sequenceOf87_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_sequenceOf87_4,
	1,	/* Single element */
	&asn_SPC_sequenceOf87_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EncryptedDeviceChangeData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EncryptedDeviceChangeData, controlRefTemplate),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ControlRefTemplate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"controlRefTemplate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EncryptedDeviceChangeData, eacSmdpOtpk),
		(ASN_TAG_CLASS_APPLICATION | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eacSmdpOtpk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EncryptedDeviceChangeData, sequenceOf87),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_sequenceOf87_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sequenceOf87"
		},
};
static const ber_tlv_tag_t asn_DEF_EncryptedDeviceChangeData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EncryptedDeviceChangeData_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (73 << 2)), 1, 0, 0 }, /* eacSmdpOtpk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* sequenceOf87 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 } /* controlRefTemplate */
};
asn_SEQUENCE_specifics_t asn_SPC_EncryptedDeviceChangeData_specs_1 = {
	sizeof(struct EncryptedDeviceChangeData),
	offsetof(struct EncryptedDeviceChangeData, _asn_ctx),
	asn_MAP_EncryptedDeviceChangeData_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EncryptedDeviceChangeData = {
	"EncryptedDeviceChangeData",
	"EncryptedDeviceChangeData",
	&asn_OP_SEQUENCE,
	asn_DEF_EncryptedDeviceChangeData_tags_1,
	sizeof(asn_DEF_EncryptedDeviceChangeData_tags_1)
		/sizeof(asn_DEF_EncryptedDeviceChangeData_tags_1[0]), /* 1 */
	asn_DEF_EncryptedDeviceChangeData_tags_1,	/* Same as above */
	sizeof(asn_DEF_EncryptedDeviceChangeData_tags_1)
		/sizeof(asn_DEF_EncryptedDeviceChangeData_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EncryptedDeviceChangeData_1,
	3,	/* Elements count */
	&asn_SPC_EncryptedDeviceChangeData_specs_1	/* Additional specs */
};

