/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EnterpriseConfiguration.h"

static int
memb_enterpriseName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_enterpriseName_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_enterpriseName_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_enterpriseRules_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnterpriseConfiguration__enterpriseRules, enterpriseRuleBits),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enterpriseRuleBits"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnterpriseConfiguration__enterpriseRules, numberOfNonEnterpriseProfiles),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfNonEnterpriseProfiles"
		},
};
static const ber_tlv_tag_t asn_DEF_enterpriseRules_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_enterpriseRules_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* enterpriseRuleBits */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* numberOfNonEnterpriseProfiles */
};
static asn_SEQUENCE_specifics_t asn_SPC_enterpriseRules_specs_4 = {
	sizeof(struct EnterpriseConfiguration__enterpriseRules),
	offsetof(struct EnterpriseConfiguration__enterpriseRules, _asn_ctx),
	asn_MAP_enterpriseRules_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_enterpriseRules_4 = {
	"enterpriseRules",
	"enterpriseRules",
	&asn_OP_SEQUENCE,
	asn_DEF_enterpriseRules_tags_4,
	sizeof(asn_DEF_enterpriseRules_tags_4)
		/sizeof(asn_DEF_enterpriseRules_tags_4[0]) - 1, /* 1 */
	asn_DEF_enterpriseRules_tags_4,	/* Same as above */
	sizeof(asn_DEF_enterpriseRules_tags_4)
		/sizeof(asn_DEF_enterpriseRules_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_enterpriseRules_4,
	2,	/* Elements count */
	&asn_SPC_enterpriseRules_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EnterpriseConfiguration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnterpriseConfiguration, enterpriseOid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enterpriseOid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EnterpriseConfiguration, enterpriseName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_enterpriseName_constr_3, &asn_PER_memb_enterpriseName_constr_3,  memb_enterpriseName_constraint_1 },
		0, 0, /* No default value */
		"enterpriseName"
		},
	{ ATF_POINTER, 1, offsetof(struct EnterpriseConfiguration, enterpriseRules),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_enterpriseRules_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enterpriseRules"
		},
};
static const int asn_MAP_EnterpriseConfiguration_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_EnterpriseConfiguration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EnterpriseConfiguration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* enterpriseOid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* enterpriseName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* enterpriseRules */
};
asn_SEQUENCE_specifics_t asn_SPC_EnterpriseConfiguration_specs_1 = {
	sizeof(struct EnterpriseConfiguration),
	offsetof(struct EnterpriseConfiguration, _asn_ctx),
	asn_MAP_EnterpriseConfiguration_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_EnterpriseConfiguration_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EnterpriseConfiguration = {
	"EnterpriseConfiguration",
	"EnterpriseConfiguration",
	&asn_OP_SEQUENCE,
	asn_DEF_EnterpriseConfiguration_tags_1,
	sizeof(asn_DEF_EnterpriseConfiguration_tags_1)
		/sizeof(asn_DEF_EnterpriseConfiguration_tags_1[0]), /* 1 */
	asn_DEF_EnterpriseConfiguration_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnterpriseConfiguration_tags_1)
		/sizeof(asn_DEF_EnterpriseConfiguration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EnterpriseConfiguration_1,
	3,	/* Elements count */
	&asn_SPC_EnterpriseConfiguration_specs_1	/* Additional specs */
};

