/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EnterpriseConfiguration_H_
#define	_EnterpriseConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OBJECT_IDENTIFIER.h>
#include <UTF8String.h>
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnterpriseConfiguration__enterpriseRules__enterpriseRuleBits {
	EnterpriseConfiguration__enterpriseRules__enterpriseRuleBits_referenceEnterpriseRule	= 0,
	EnterpriseConfiguration__enterpriseRules__enterpriseRuleBits_priorityEnterpriseProfile	= 1,
	EnterpriseConfiguration__enterpriseRules__enterpriseRuleBits_onlyEnterpriseProfilesCanBeInstalled	= 2
} e_EnterpriseConfiguration__enterpriseRules__enterpriseRuleBits;

/* EnterpriseConfiguration */
typedef struct EnterpriseConfiguration {
	OBJECT_IDENTIFIER_t	 enterpriseOid;
	UTF8String_t	 enterpriseName;
	struct EnterpriseConfiguration__enterpriseRules {
		BIT_STRING_t	 enterpriseRuleBits;
		long	 numberOfNonEnterpriseProfiles;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *enterpriseRules;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnterpriseConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnterpriseConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_EnterpriseConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_EnterpriseConfiguration_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EnterpriseConfiguration_H_ */
#include <asn_internal.h>
