/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EsipaMessageFromIpaToEim.h"

static asn_oer_constraints_t asn_OER_type_EsipaMessageFromIpaToEim_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_EsipaMessageFromIpaToEim_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  7 }	/* (0..7,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_EsipaMessageFromIpaToEim_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.initiateAuthenticationRequestEsipa),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateAuthenticationRequestEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateAuthenticationRequestEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.authenticateClientRequestEsipa),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthenticateClientRequestEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authenticateClientRequestEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.getBoundProfilePackageRequestEsipa),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetBoundProfilePackageRequestEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getBoundProfilePackageRequestEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.cancelSessionRequestEsipa),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionRequestEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionRequestEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.handleNotificationEsipa),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HandleNotificationEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"handleNotificationEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.transferEimPackageResponse),
		(ASN_TAG_CLASS_CONTEXT | (78 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransferEimPackageResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transferEimPackageResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.getEimPackageRequest),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetEimPackageRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getEimPackageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromIpaToEim, choice.provideEimPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProvideEimPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"provideEimPackageResult"
		},
};
static const unsigned asn_MAP_EsipaMessageFromIpaToEim_to_canonical_1[] = { 0, 2, 1, 4, 3, 5, 6, 7 };
static const unsigned asn_MAP_EsipaMessageFromIpaToEim_from_canonical_1[] = { 0, 2, 1, 4, 3, 5, 6, 7 };
static const asn_TYPE_tag2member_t asn_MAP_EsipaMessageFromIpaToEim_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 0, 0, 0 }, /* initiateAuthenticationRequestEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 2, 0, 0 }, /* getBoundProfilePackageRequestEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 1, 0, 0 }, /* authenticateClientRequestEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 4, 0, 0 }, /* handleNotificationEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 3, 0, 0 }, /* cancelSessionRequestEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (78 << 2)), 5, 0, 0 }, /* transferEimPackageResponse */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 6, 0, 0 }, /* getEimPackageRequest */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 7, 0, 0 } /* provideEimPackageResult */
};
static asn_CHOICE_specifics_t asn_SPC_EsipaMessageFromIpaToEim_specs_1 = {
	sizeof(struct EsipaMessageFromIpaToEim),
	offsetof(struct EsipaMessageFromIpaToEim, _asn_ctx),
	offsetof(struct EsipaMessageFromIpaToEim, present),
	sizeof(((struct EsipaMessageFromIpaToEim *)0)->present),
	asn_MAP_EsipaMessageFromIpaToEim_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_EsipaMessageFromIpaToEim_to_canonical_1,
	asn_MAP_EsipaMessageFromIpaToEim_from_canonical_1,
	8	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EsipaMessageFromIpaToEim = {
	"EsipaMessageFromIpaToEim",
	"EsipaMessageFromIpaToEim",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_EsipaMessageFromIpaToEim_constr_1, &asn_PER_type_EsipaMessageFromIpaToEim_constr_1, CHOICE_constraint },
	asn_MBR_EsipaMessageFromIpaToEim_1,
	8,	/* Elements count */
	&asn_SPC_EsipaMessageFromIpaToEim_specs_1	/* Additional specs */
};

