/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EuiccRspCapability_H_
#define	_EuiccRspCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuiccRspCapability {
	EuiccRspCapability_additionalProfile	= 0,
	EuiccRspCapability_loadCrlSupport	= 1,
	EuiccRspCapability_rpmSupport	= 2,
	EuiccRspCapability_testProfileSupport	= 3,
	EuiccRspCapability_deviceInfoExtensibilitySupport	= 4,
	EuiccRspCapability_serviceSpecificDataSupport	= 5,
	EuiccRspCapability_hriServerAddressSupport	= 6,
	EuiccRspCapability_serviceProviderMessageSupport	= 7,
	EuiccRspCapability_lpaProxySupport	= 8,
	EuiccRspCapability_enterpriseProfilesSupport	= 9,
	EuiccRspCapability_serviceDescriptionSupport	= 10,
	EuiccRspCapability_deviceChangeSupport	= 11,
	EuiccRspCapability_encryptedDeviceChangeDataSupport	= 12,
	EuiccRspCapability_estimatedProfileSizeIndicationSupport	= 13,
	EuiccRspCapability_profileSizeInProfilesInfoSupport	= 14,
	EuiccRspCapability_crlStaplingV3Support	= 15,
	EuiccRspCapability_certChainV3VerificationSupport	= 16,
	EuiccRspCapability_signedSmdsResponseV3Support	= 17,
	EuiccRspCapability_euiccRspCapInInfo1	= 18,
	EuiccRspCapability_osUpdateSupport	= 19,
	EuiccRspCapability_cancelForEmptySpnPnSupport	= 20,
	EuiccRspCapability_updateNotifConfigInfoSupport	= 21,
	EuiccRspCapability_updateMetadataV3Support	= 22,
	EuiccRspCapability_v3ObjectsInCtxParamsCASupport	= 23,
	EuiccRspCapability_pushServiceRegistrationSupport	= 24
} e_EuiccRspCapability;

/* EuiccRspCapability */
typedef BIT_STRING_t	 EuiccRspCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccRspCapability;
asn_struct_free_f EuiccRspCapability_free;
asn_struct_print_f EuiccRspCapability_print;
asn_constr_check_f EuiccRspCapability_constraint;
ber_type_decoder_f EuiccRspCapability_decode_ber;
der_type_encoder_f EuiccRspCapability_encode_der;
xer_type_decoder_f EuiccRspCapability_decode_xer;
xer_type_encoder_f EuiccRspCapability_encode_xer;
oer_type_decoder_f EuiccRspCapability_decode_oer;
oer_type_encoder_f EuiccRspCapability_encode_oer;
per_type_decoder_f EuiccRspCapability_decode_uper;
per_type_encoder_f EuiccRspCapability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccRspCapability_H_ */
#include <asn_internal.h>
