/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EuiccConfiguredDataResponse_H_
#define	_EuiccConfiguredDataResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "SubjectKeyIdentifier.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct EuiccConfiguredDataResponse__ciList__Member {
	SubjectKeyIdentifier_t	 ciPKId;
	UTF8String_t	 ciName;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccConfiguredDataResponse__ciList__Member;

/* EuiccConfiguredDataResponse */
typedef struct EuiccConfiguredDataResponse {
	UTF8String_t	*defaultDpAddress	/* OPTIONAL */;
	UTF8String_t	 rootDsAddress;
	struct EuiccConfiguredDataResponse__additionalRootDsAddresses {
		A_SEQUENCE_OF(UTF8String_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *additionalRootDsAddresses;
	SubjectKeyIdentifier_t	*allowedCiPKId	/* OPTIONAL */;
	struct EuiccConfiguredDataResponse__ciList {
		A_SEQUENCE_OF(EuiccConfiguredDataResponse__ciList__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ciList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccConfiguredDataResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccConfiguredDataResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccConfiguredDataResponse_H_ */
#include <asn_internal.h>
