/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EuiccSign_H_
#define	_EuiccSign_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccSign */
typedef OCTET_STRING_t	 EuiccSign_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccSign;
asn_struct_free_f EuiccSign_free;
asn_struct_print_f EuiccSign_print;
asn_constr_check_f EuiccSign_constraint;
ber_type_decoder_f EuiccSign_decode_ber;
der_type_encoder_f EuiccSign_encode_der;
xer_type_decoder_f EuiccSign_decode_xer;
xer_type_encoder_f EuiccSign_encode_xer;
oer_type_decoder_f EuiccSign_decode_oer;
oer_type_encoder_f EuiccSign_encode_oer;
per_type_decoder_f EuiccSign_decode_uper;
per_type_encoder_f EuiccSign_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccSign_H_ */
#include <asn_internal.h>
