/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EUICCSigned3_H_
#define	_EUICCSigned3_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include <OCTET_STRING.h>
#include "Octet32.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VendorSpecificExtension;

/* EUICCSigned3 */
typedef struct EUICCSigned3 {
	TransactionId_t	 transactionId;
	OCTET_STRING_t	*eacEuiccOtpk	/* OPTIONAL */;
	Octet32_t	*hashCc	/* OPTIONAL */;
	struct VendorSpecificExtension	*additionalInformation	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUICCSigned3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUICCSigned3;
extern asn_SEQUENCE_specifics_t asn_SPC_EUICCSigned3_specs_1;
extern asn_TYPE_member_t asn_MBR_EUICCSigned3_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VendorSpecificExtension.h"

#endif	/* _EUICCSigned3_H_ */
#include <asn_internal.h>
