/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EUICCSigned3.h"

asn_TYPE_member_t asn_MBR_EUICCSigned3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCSigned3, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_POINTER, 3, offsetof(struct EUICCSigned3, eacEuiccOtpk),
		(ASN_TAG_CLASS_APPLICATION | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eacEuiccOtpk"
		},
	{ ATF_POINTER, 2, offsetof(struct EUICCSigned3, hashCc),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Octet32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashCc"
		},
	{ ATF_POINTER, 1, offsetof(struct EUICCSigned3, additionalInformation),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalInformation"
		},
};
static const int asn_MAP_EUICCSigned3_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_EUICCSigned3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EUICCSigned3_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* hashCc */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 }, /* additionalInformation */
    { (ASN_TAG_CLASS_APPLICATION | (73 << 2)), 1, 0, 0 }, /* eacEuiccOtpk */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* transactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_EUICCSigned3_specs_1 = {
	sizeof(struct EUICCSigned3),
	offsetof(struct EUICCSigned3, _asn_ctx),
	asn_MAP_EUICCSigned3_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_EUICCSigned3_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EUICCSigned3 = {
	"EUICCSigned3",
	"EUICCSigned3",
	&asn_OP_SEQUENCE,
	asn_DEF_EUICCSigned3_tags_1,
	sizeof(asn_DEF_EUICCSigned3_tags_1)
		/sizeof(asn_DEF_EUICCSigned3_tags_1[0]), /* 1 */
	asn_DEF_EUICCSigned3_tags_1,	/* Same as above */
	sizeof(asn_DEF_EUICCSigned3_tags_1)
		/sizeof(asn_DEF_EUICCSigned3_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EUICCSigned3_1,
	4,	/* Elements count */
	&asn_SPC_EUICCSigned3_specs_1	/* Additional specs */
};

