/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EuiccConfiguredDataResponse.h"

static asn_TYPE_member_t asn_MBR_additionalRootDsAddresses_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_additionalRootDsAddresses_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_additionalRootDsAddresses_specs_4 = {
	sizeof(struct EuiccConfiguredDataResponse__additionalRootDsAddresses),
	offsetof(struct EuiccConfiguredDataResponse__additionalRootDsAddresses, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_additionalRootDsAddresses_4 = {
	"additionalRootDsAddresses",
	"additionalRootDsAddresses",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_additionalRootDsAddresses_tags_4,
	sizeof(asn_DEF_additionalRootDsAddresses_tags_4)
		/sizeof(asn_DEF_additionalRootDsAddresses_tags_4[0]) - 1, /* 1 */
	asn_DEF_additionalRootDsAddresses_tags_4,	/* Same as above */
	sizeof(asn_DEF_additionalRootDsAddresses_tags_4)
		/sizeof(asn_DEF_additionalRootDsAddresses_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_additionalRootDsAddresses_4,
	1,	/* Single element */
	&asn_SPC_additionalRootDsAddresses_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccConfiguredDataResponse__ciList__Member, ciPKId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ciPKId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccConfiguredDataResponse__ciList__Member, ciName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ciName"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ciPKId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ciName */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_8 = {
	sizeof(struct EuiccConfiguredDataResponse__ciList__Member),
	offsetof(struct EuiccConfiguredDataResponse__ciList__Member, _asn_ctx),
	asn_MAP_Member_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_8 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_8,
	sizeof(asn_DEF_Member_tags_8)
		/sizeof(asn_DEF_Member_tags_8[0]), /* 1 */
	asn_DEF_Member_tags_8,	/* Same as above */
	sizeof(asn_DEF_Member_tags_8)
		/sizeof(asn_DEF_Member_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_8,
	2,	/* Elements count */
	&asn_SPC_Member_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ciList_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ciList_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ciList_specs_7 = {
	sizeof(struct EuiccConfiguredDataResponse__ciList),
	offsetof(struct EuiccConfiguredDataResponse__ciList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ciList_7 = {
	"ciList",
	"ciList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ciList_tags_7,
	sizeof(asn_DEF_ciList_tags_7)
		/sizeof(asn_DEF_ciList_tags_7[0]) - 1, /* 1 */
	asn_DEF_ciList_tags_7,	/* Same as above */
	sizeof(asn_DEF_ciList_tags_7)
		/sizeof(asn_DEF_ciList_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_ciList_7,
	1,	/* Single element */
	&asn_SPC_ciList_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EuiccConfiguredDataResponse_1[] = {
	{ ATF_POINTER, 1, offsetof(struct EuiccConfiguredDataResponse, defaultDpAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultDpAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccConfiguredDataResponse, rootDsAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rootDsAddress"
		},
	{ ATF_POINTER, 3, offsetof(struct EuiccConfiguredDataResponse, additionalRootDsAddresses),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_additionalRootDsAddresses_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"additionalRootDsAddresses"
		},
	{ ATF_POINTER, 2, offsetof(struct EuiccConfiguredDataResponse, allowedCiPKId),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allowedCiPKId"
		},
	{ ATF_POINTER, 1, offsetof(struct EuiccConfiguredDataResponse, ciList),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ciList_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ciList"
		},
};
static const int asn_MAP_EuiccConfiguredDataResponse_oms_1[] = { 0, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_EuiccConfiguredDataResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EuiccConfiguredDataResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* defaultDpAddress */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rootDsAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* additionalRootDsAddresses */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* allowedCiPKId */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ciList */
};
static asn_SEQUENCE_specifics_t asn_SPC_EuiccConfiguredDataResponse_specs_1 = {
	sizeof(struct EuiccConfiguredDataResponse),
	offsetof(struct EuiccConfiguredDataResponse, _asn_ctx),
	asn_MAP_EuiccConfiguredDataResponse_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_EuiccConfiguredDataResponse_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EuiccConfiguredDataResponse = {
	"EuiccConfiguredDataResponse",
	"EuiccConfiguredDataResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_EuiccConfiguredDataResponse_tags_1,
	sizeof(asn_DEF_EuiccConfiguredDataResponse_tags_1)
		/sizeof(asn_DEF_EuiccConfiguredDataResponse_tags_1[0]) - 1, /* 1 */
	asn_DEF_EuiccConfiguredDataResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_EuiccConfiguredDataResponse_tags_1)
		/sizeof(asn_DEF_EuiccConfiguredDataResponse_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EuiccConfiguredDataResponse_1,
	5,	/* Elements count */
	&asn_SPC_EuiccConfiguredDataResponse_specs_1	/* Additional specs */
};

