/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_EventRecordV3_H_
#define	_EventRecordV3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OperatorId;

/* EventRecordV3 */
typedef struct EventRecordV3 {
	UTF8String_t	 eventId;
	UTF8String_t	 rspServerAddress;
	long	 eventType;
	struct EventRecordV3__hashedIccids {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *hashedIccids;
	OCTET_STRING_t	*salt	/* OPTIONAL */;
	UTF8String_t	*serviceProviderName	/* OPTIONAL */;
	struct OperatorId	*operatorId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EventRecordV3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventRecordV3;
extern asn_SEQUENCE_specifics_t asn_SPC_EventRecordV3_specs_1;
extern asn_TYPE_member_t asn_MBR_EventRecordV3_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OperatorId.h"

#endif	/* _EventRecordV3_H_ */
#include <asn_internal.h>
