/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "EventRecordV3.h"

static int
memb_OCTET_STRING_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size == 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_salt_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 8 && size <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_serviceProviderName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_Member_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	32	/* (SIZE(32..32)) */};
static asn_per_constraints_t asn_PER_memb_Member_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  32,  32 }	/* (SIZE(32..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_salt_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(8..16)) */};
static asn_per_constraints_t asn_PER_memb_salt_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  8,  16 }	/* (SIZE(8..16)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_serviceProviderName_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..MAX)) */};
static asn_per_constraints_t asn_PER_memb_serviceProviderName_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_hashedIccids_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_Member_constr_6, &asn_PER_memb_Member_constr_6,  memb_OCTET_STRING_constraint_5 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_hashedIccids_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_hashedIccids_specs_5 = {
	sizeof(struct EventRecordV3__hashedIccids),
	offsetof(struct EventRecordV3__hashedIccids, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_hashedIccids_5 = {
	"hashedIccids",
	"hashedIccids",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_hashedIccids_tags_5,
	sizeof(asn_DEF_hashedIccids_tags_5)
		/sizeof(asn_DEF_hashedIccids_tags_5[0]), /* 1 */
	asn_DEF_hashedIccids_tags_5,	/* Same as above */
	sizeof(asn_DEF_hashedIccids_tags_5)
		/sizeof(asn_DEF_hashedIccids_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_hashedIccids_5,
	1,	/* Single element */
	&asn_SPC_hashedIccids_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_EventRecordV3_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EventRecordV3, eventId),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventRecordV3, rspServerAddress),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rspServerAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EventRecordV3, eventType),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventType"
		},
	{ ATF_POINTER, 4, offsetof(struct EventRecordV3, hashedIccids),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_hashedIccids_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashedIccids"
		},
	{ ATF_POINTER, 3, offsetof(struct EventRecordV3, salt),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_salt_constr_7, &asn_PER_memb_salt_constr_7,  memb_salt_constraint_1 },
		0, 0, /* No default value */
		"salt"
		},
	{ ATF_POINTER, 2, offsetof(struct EventRecordV3, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ &asn_OER_memb_serviceProviderName_constr_8, &asn_PER_memb_serviceProviderName_constr_8,  memb_serviceProviderName_constraint_1 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_POINTER, 1, offsetof(struct EventRecordV3, operatorId),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OperatorId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"operatorId"
		},
};
static const int asn_MAP_EventRecordV3_oms_1[] = { 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_EventRecordV3_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EventRecordV3_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 0 }, /* eventType */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 4, 0, 0 }, /* salt */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 0, 0, 1 }, /* eventId */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, -1, 0 }, /* rspServerAddress */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 0 }, /* hashedIccids */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 5, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 6, 0, 0 } /* operatorId */
};
asn_SEQUENCE_specifics_t asn_SPC_EventRecordV3_specs_1 = {
	sizeof(struct EventRecordV3),
	offsetof(struct EventRecordV3, _asn_ctx),
	asn_MAP_EventRecordV3_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_EventRecordV3_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EventRecordV3 = {
	"EventRecordV3",
	"EventRecordV3",
	&asn_OP_SEQUENCE,
	asn_DEF_EventRecordV3_tags_1,
	sizeof(asn_DEF_EventRecordV3_tags_1)
		/sizeof(asn_DEF_EventRecordV3_tags_1[0]), /* 1 */
	asn_DEF_EventRecordV3_tags_1,	/* Same as above */
	sizeof(asn_DEF_EventRecordV3_tags_1)
		/sizeof(asn_DEF_EventRecordV3_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EventRecordV3_1,
	7,	/* Elements count */
	&asn_SPC_EventRecordV3_specs_1	/* Additional specs */
};

