/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "GetEimPackageResponse.h"

static asn_oer_constraints_t asn_OER_type_GetEimPackageResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_GetEimPackageResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_GetEimPackageResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetEimPackageResponse, choice.euiccPackageRequest),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetEimPackageResponse, choice.ipaEuiccDataRequest),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpaEuiccDataRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipaEuiccDataRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetEimPackageResponse, choice.profileDownloadTriggerRequest),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileDownloadTriggerRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileDownloadTriggerRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetEimPackageResponse, choice.eimPackageError),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimPackageError"
		},
};
static const unsigned asn_MAP_GetEimPackageResponse_to_canonical_1[] = { 3, 0, 1, 2 };
static const unsigned asn_MAP_GetEimPackageResponse_from_canonical_1[] = { 1, 2, 3, 0 };
static const ber_tlv_tag_t asn_DEF_GetEimPackageResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (79 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetEimPackageResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 3, 0, 0 }, /* eimPackageError */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 }, /* euiccPackageRequest */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 1, 0, 0 }, /* ipaEuiccDataRequest */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 2, 0, 0 } /* profileDownloadTriggerRequest */
};
asn_CHOICE_specifics_t asn_SPC_GetEimPackageResponse_specs_1 = {
	sizeof(struct GetEimPackageResponse),
	offsetof(struct GetEimPackageResponse, _asn_ctx),
	offsetof(struct GetEimPackageResponse, present),
	sizeof(((struct GetEimPackageResponse *)0)->present),
	asn_MAP_GetEimPackageResponse_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_GetEimPackageResponse_to_canonical_1,
	asn_MAP_GetEimPackageResponse_from_canonical_1,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GetEimPackageResponse = {
	"GetEimPackageResponse",
	"GetEimPackageResponse",
	&asn_OP_CHOICE,
	asn_DEF_GetEimPackageResponse_tags_1,
	sizeof(asn_DEF_GetEimPackageResponse_tags_1)
		/sizeof(asn_DEF_GetEimPackageResponse_tags_1[0]), /* 1 */
	asn_DEF_GetEimPackageResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetEimPackageResponse_tags_1)
		/sizeof(asn_DEF_GetEimPackageResponse_tags_1[0]), /* 1 */
	{ &asn_OER_type_GetEimPackageResponse_constr_1, &asn_PER_type_GetEimPackageResponse_constr_1, CHOICE_constraint },
	asn_MBR_GetEimPackageResponse_1,
	4,	/* Elements count */
	&asn_SPC_GetEimPackageResponse_specs_1	/* Additional specs */
};

