/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ListProfileInfo.h"

static asn_oer_constraints_t asn_OER_type_searchCriteria_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_searchCriteria_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_searchCriteria_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ListProfileInfo__searchCriteria, choice.iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ListProfileInfo__searchCriteria, choice.profileOwnerOid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwnerOid"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_searchCriteria_tag2el_2[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* profileOwnerOid */
};
static asn_CHOICE_specifics_t asn_SPC_searchCriteria_specs_2 = {
	sizeof(struct ListProfileInfo__searchCriteria),
	offsetof(struct ListProfileInfo__searchCriteria, _asn_ctx),
	offsetof(struct ListProfileInfo__searchCriteria, present),
	sizeof(((struct ListProfileInfo__searchCriteria *)0)->present),
	asn_MAP_searchCriteria_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_searchCriteria_2 = {
	"searchCriteria",
	"searchCriteria",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_searchCriteria_constr_2, &asn_PER_type_searchCriteria_constr_2, CHOICE_constraint },
	asn_MBR_searchCriteria_2,
	2,	/* Elements count */
	&asn_SPC_searchCriteria_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ListProfileInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ListProfileInfo, searchCriteria),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_searchCriteria_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"searchCriteria"
		},
	{ ATF_POINTER, 1, offsetof(struct ListProfileInfo, tagList),
		(ASN_TAG_CLASS_APPLICATION | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tagList"
		},
};
static const int asn_MAP_ListProfileInfo_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_ListProfileInfo_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ListProfileInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (28 << 2)), 1, 0, 0 }, /* tagList */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* searchCriteria */
};
asn_SEQUENCE_specifics_t asn_SPC_ListProfileInfo_specs_1 = {
	sizeof(struct ListProfileInfo),
	offsetof(struct ListProfileInfo, _asn_ctx),
	asn_MAP_ListProfileInfo_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_ListProfileInfo_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ListProfileInfo = {
	"ListProfileInfo",
	"ListProfileInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ListProfileInfo_tags_1,
	sizeof(asn_DEF_ListProfileInfo_tags_1)
		/sizeof(asn_DEF_ListProfileInfo_tags_1[0]) - 1, /* 1 */
	asn_DEF_ListProfileInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ListProfileInfo_tags_1)
		/sizeof(asn_DEF_ListProfileInfo_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ListProfileInfo_1,
	2,	/* Elements count */
	&asn_SPC_ListProfileInfo_specs_1	/* Additional specs */
};

