/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ListProfileInfo_H_
#define	_ListProfileInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "Iccid.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ListProfileInfo__searchCriteria_PR {
	ListProfileInfo__searchCriteria_PR_NOTHING,	/* No components present */
	ListProfileInfo__searchCriteria_PR_iccid,
	ListProfileInfo__searchCriteria_PR_profileOwnerOid
	/* Extensions may appear below */
	
} ListProfileInfo__searchCriteria_PR;

/* ListProfileInfo */
typedef struct ListProfileInfo {
	struct ListProfileInfo__searchCriteria {
		ListProfileInfo__searchCriteria_PR present;
		union ListProfileInfo__searchCriteria_u {
			Iccid_t	 iccid;
			OBJECT_IDENTIFIER_t	 profileOwnerOid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} searchCriteria;
	OCTET_STRING_t	*tagList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListProfileInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListProfileInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_ListProfileInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_ListProfileInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ListProfileInfo_H_ */
#include <asn_internal.h>
