/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadRpmPackageResultNotSigned_H_
#define	_LoadRpmPackageResultNotSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "LoadRpmPackageErrorCodeNotSigned.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoadRpmPackageResultNotSigned */
typedef struct LoadRpmPackageResultNotSigned {
	TransactionId_t	 transactionId;
	LoadRpmPackageErrorCodeNotSigned_t	 loadRpmPackageErrorCodeNotSigned;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadRpmPackageResultNotSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageResultNotSigned;
extern asn_SEQUENCE_specifics_t asn_SPC_LoadRpmPackageResultNotSigned_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadRpmPackageResultNotSigned_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LoadRpmPackageResultNotSigned_H_ */
#include <asn_internal.h>
