/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "LoadRpmPackageResult.h"

static asn_oer_constraints_t asn_OER_type_LoadRpmPackageResult_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_LoadRpmPackageResult_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_LoadRpmPackageResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LoadRpmPackageResult, choice.loadRpmPackageResultSigned),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LoadRpmPackageResultSigned,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"loadRpmPackageResultSigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoadRpmPackageResult, choice.loadRpmPackageResultNotSigned),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LoadRpmPackageResultNotSigned,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"loadRpmPackageResultNotSigned"
		},
};
static const ber_tlv_tag_t asn_DEF_LoadRpmPackageResult_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (68 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LoadRpmPackageResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* loadRpmPackageResultSigned */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* loadRpmPackageResultNotSigned */
};
static asn_CHOICE_specifics_t asn_SPC_LoadRpmPackageResult_specs_1 = {
	sizeof(struct LoadRpmPackageResult),
	offsetof(struct LoadRpmPackageResult, _asn_ctx),
	offsetof(struct LoadRpmPackageResult, present),
	sizeof(((struct LoadRpmPackageResult *)0)->present),
	asn_MAP_LoadRpmPackageResult_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageResult = {
	"LoadRpmPackageResult",
	"LoadRpmPackageResult",
	&asn_OP_CHOICE,
	asn_DEF_LoadRpmPackageResult_tags_1,
	sizeof(asn_DEF_LoadRpmPackageResult_tags_1)
		/sizeof(asn_DEF_LoadRpmPackageResult_tags_1[0]), /* 1 */
	asn_DEF_LoadRpmPackageResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_LoadRpmPackageResult_tags_1)
		/sizeof(asn_DEF_LoadRpmPackageResult_tags_1[0]), /* 1 */
	{ &asn_OER_type_LoadRpmPackageResult_constr_1, &asn_PER_type_LoadRpmPackageResult_constr_1, CHOICE_constraint },
	asn_MBR_LoadRpmPackageResult_1,
	2,	/* Elements count */
	&asn_SPC_LoadRpmPackageResult_specs_1	/* Additional specs */
};

