/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadRpmPackageResultDataSigned_H_
#define	_LoadRpmPackageResultDataSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "NotificationMetadata.h"
#include <OBJECT_IDENTIFIER.h>
#include "LoadRpmPackageErrorCodeSigned.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadRpmPackageResultDataSigned__finalResult_PR {
	LoadRpmPackageResultDataSigned__finalResult_PR_NOTHING,	/* No components present */
	LoadRpmPackageResultDataSigned__finalResult_PR_rpmPackageExecutionResult,
	LoadRpmPackageResultDataSigned__finalResult_PR_loadRpmPackageErrorCodeSigned
	/* Extensions may appear below */
	
} LoadRpmPackageResultDataSigned__finalResult_PR;

/* Forward declarations */
struct RpmCommandResult;

/* LoadRpmPackageResultDataSigned */
typedef struct LoadRpmPackageResultDataSigned {
	TransactionId_t	 transactionId;
	NotificationMetadata_t	 notificationMetadata;
	OBJECT_IDENTIFIER_t	 smdpOid;
	struct LoadRpmPackageResultDataSigned__finalResult {
		LoadRpmPackageResultDataSigned__finalResult_PR present;
		union LoadRpmPackageResultDataSigned__finalResult_u {
			struct LoadRpmPackageResultDataSigned__finalResult__rpmPackageExecutionResult {
				A_SEQUENCE_OF(struct RpmCommandResult) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} rpmPackageExecutionResult;
			LoadRpmPackageErrorCodeSigned_t	 loadRpmPackageErrorCodeSigned;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} finalResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadRpmPackageResultDataSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageResultDataSigned;
extern asn_SEQUENCE_specifics_t asn_SPC_LoadRpmPackageResultDataSigned_specs_1;
extern asn_TYPE_member_t asn_MBR_LoadRpmPackageResultDataSigned_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RpmCommandResult.h"

#endif	/* _LoadRpmPackageResultDataSigned_H_ */
#include <asn_internal.h>
