/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "LoadRpmPackageRequest.h"

static asn_TYPE_member_t asn_MBR_LoadRpmPackageRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LoadRpmPackageRequest, smdpSigned3),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LoadRpmPackageRequest, smdpSignature3),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature3"
		},
	{ ATF_POINTER, 1, offsetof(struct LoadRpmPackageRequest, targetEsimPort),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"targetEsimPort"
		},
};
static const int asn_MAP_LoadRpmPackageRequest_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_LoadRpmPackageRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LoadRpmPackageRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 0 }, /* targetEsimPort */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* smdpSigned3 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 } /* smdpSignature3 */
};
static asn_SEQUENCE_specifics_t asn_SPC_LoadRpmPackageRequest_specs_1 = {
	sizeof(struct LoadRpmPackageRequest),
	offsetof(struct LoadRpmPackageRequest, _asn_ctx),
	asn_MAP_LoadRpmPackageRequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LoadRpmPackageRequest_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageRequest = {
	"LoadRpmPackageRequest",
	"LoadRpmPackageRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_LoadRpmPackageRequest_tags_1,
	sizeof(asn_DEF_LoadRpmPackageRequest_tags_1)
		/sizeof(asn_DEF_LoadRpmPackageRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_LoadRpmPackageRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_LoadRpmPackageRequest_tags_1)
		/sizeof(asn_DEF_LoadRpmPackageRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LoadRpmPackageRequest_1,
	3,	/* Elements count */
	&asn_SPC_LoadRpmPackageRequest_specs_1	/* Additional specs */
};

