/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadRpmPackageErrorCodeSigned_H_
#define	_LoadRpmPackageErrorCodeSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadRpmPackageErrorCodeSigned {
	LoadRpmPackageErrorCodeSigned_invalidSignature	= 2,
	LoadRpmPackageErrorCodeSigned_invalidTransactionId	= 5,
	LoadRpmPackageErrorCodeSigned_undefinedError	= 127
} e_LoadRpmPackageErrorCodeSigned;

/* LoadRpmPackageErrorCodeSigned */
typedef long	 LoadRpmPackageErrorCodeSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageErrorCodeSigned;
asn_struct_free_f LoadRpmPackageErrorCodeSigned_free;
asn_struct_print_f LoadRpmPackageErrorCodeSigned_print;
asn_constr_check_f LoadRpmPackageErrorCodeSigned_constraint;
ber_type_decoder_f LoadRpmPackageErrorCodeSigned_decode_ber;
der_type_encoder_f LoadRpmPackageErrorCodeSigned_encode_der;
xer_type_decoder_f LoadRpmPackageErrorCodeSigned_decode_xer;
xer_type_encoder_f LoadRpmPackageErrorCodeSigned_encode_xer;
oer_type_decoder_f LoadRpmPackageErrorCodeSigned_decode_oer;
oer_type_encoder_f LoadRpmPackageErrorCodeSigned_encode_oer;
per_type_decoder_f LoadRpmPackageErrorCodeSigned_decode_uper;
per_type_encoder_f LoadRpmPackageErrorCodeSigned_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadRpmPackageErrorCodeSigned_H_ */
#include <asn_internal.h>
