/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadRpmPackageResult_H_
#define	_LoadRpmPackageResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LoadRpmPackageResultSigned.h"
#include "LoadRpmPackageResultNotSigned.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadRpmPackageResult_PR {
	LoadRpmPackageResult_PR_NOTHING,	/* No components present */
	LoadRpmPackageResult_PR_loadRpmPackageResultSigned,
	LoadRpmPackageResult_PR_loadRpmPackageResultNotSigned
	/* Extensions may appear below */
	
} LoadRpmPackageResult_PR;

/* LoadRpmPackageResult */
typedef struct LoadRpmPackageResult {
	LoadRpmPackageResult_PR present;
	union LoadRpmPackageResult_u {
		LoadRpmPackageResultSigned_t	 loadRpmPackageResultSigned;
		LoadRpmPackageResultNotSigned_t	 loadRpmPackageResultNotSigned;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoadRpmPackageResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageResult;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadRpmPackageResult_H_ */
#include <asn_internal.h>
