/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LoadRpmPackageErrorCodeNotSigned_H_
#define	_LoadRpmPackageErrorCodeNotSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LoadRpmPackageErrorCodeNotSigned {
	LoadRpmPackageErrorCodeNotSigned_noSession	= 4,
	LoadRpmPackageErrorCodeNotSigned_undefinedError	= 127
} e_LoadRpmPackageErrorCodeNotSigned;

/* LoadRpmPackageErrorCodeNotSigned */
typedef long	 LoadRpmPackageErrorCodeNotSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoadRpmPackageErrorCodeNotSigned;
asn_struct_free_f LoadRpmPackageErrorCodeNotSigned_free;
asn_struct_print_f LoadRpmPackageErrorCodeNotSigned_print;
asn_constr_check_f LoadRpmPackageErrorCodeNotSigned_constraint;
ber_type_decoder_f LoadRpmPackageErrorCodeNotSigned_decode_ber;
der_type_encoder_f LoadRpmPackageErrorCodeNotSigned_encode_der;
xer_type_decoder_f LoadRpmPackageErrorCodeNotSigned_decode_xer;
xer_type_encoder_f LoadRpmPackageErrorCodeNotSigned_encode_xer;
oer_type_decoder_f LoadRpmPackageErrorCodeNotSigned_decode_oer;
oer_type_encoder_f LoadRpmPackageErrorCodeNotSigned_encode_oer;
per_type_decoder_f LoadRpmPackageErrorCodeNotSigned_decode_uper;
per_type_encoder_f LoadRpmPackageErrorCodeNotSigned_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LoadRpmPackageErrorCodeNotSigned_H_ */
#include <asn_internal.h>
