/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LocalisedTextMessage_H_
#define	_LocalisedTextMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocalisedTextMessage */
typedef struct LocalisedTextMessage {
	UTF8String_t	*languageTag	/* DEFAULT en */;
	UTF8String_t	 message;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocalisedTextMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocalisedTextMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_LocalisedTextMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_LocalisedTextMessage_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LocalisedTextMessage_H_ */
#include <asn_internal.h>
