/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LpaMode_H_
#define	_LpaMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LpaMode {
	LpaMode_lpad	= 0,
	LpaMode_lpae	= 1
} e_LpaMode;

/* LpaMode */
typedef long	 LpaMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LpaMode;
asn_struct_free_f LpaMode_free;
asn_struct_print_f LpaMode_print;
asn_constr_check_f LpaMode_constraint;
ber_type_decoder_f LpaMode_decode_ber;
der_type_encoder_f LpaMode_encode_der;
xer_type_decoder_f LpaMode_decode_xer;
xer_type_encoder_f LpaMode_encode_xer;
oer_type_decoder_f LpaMode_decode_oer;
oer_type_encoder_f LpaMode_encode_oer;
per_type_decoder_f LpaMode_decode_uper;
per_type_encoder_f LpaMode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LpaMode_H_ */
#include <asn_internal.h>
