/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_LpaRspCapability_H_
#define	_LpaRspCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LpaRspCapability {
	LpaRspCapability_crlStaplingV3Support	= 0,
	LpaRspCapability_certChainV3Support	= 1,
	LpaRspCapability_apduApiSupport	= 2,
	LpaRspCapability_enterpriseCapableDevice	= 3,
	LpaRspCapability_lpaProxySupport	= 4,
	LpaRspCapability_signedSmdsResponseV3Support	= 5,
	LpaRspCapability_euiccCiUpdateSupport	= 6,
	LpaRspCapability_eventCheckingSupport	= 7,
	LpaRspCapability_pushServiceSupport	= 8,
	LpaRspCapability_pendingOperationAlertingSupport	= 9
} e_LpaRspCapability;

/* LpaRspCapability */
typedef BIT_STRING_t	 LpaRspCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LpaRspCapability;
asn_struct_free_f LpaRspCapability_free;
asn_struct_print_f LpaRspCapability_print;
asn_constr_check_f LpaRspCapability_constraint;
ber_type_decoder_f LpaRspCapability_decode_ber;
der_type_encoder_f LpaRspCapability_encode_der;
xer_type_decoder_f LpaRspCapability_decode_xer;
xer_type_encoder_f LpaRspCapability_encode_xer;
oer_type_decoder_f LpaRspCapability_decode_oer;
oer_type_encoder_f LpaRspCapability_encode_oer;
per_type_decoder_f LpaRspCapability_decode_uper;
per_type_encoder_f LpaRspCapability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LpaRspCapability_H_ */
#include <asn_internal.h>
