/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_MatchingIdSource_H_
#define	_MatchingIdSource_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <OBJECT_IDENTIFIER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MatchingIdSource_PR {
	MatchingIdSource_PR_NOTHING,	/* No components present */
	MatchingIdSource_PR_none,
	MatchingIdSource_PR_activationCode,
	MatchingIdSource_PR_smdsOid
	/* Extensions may appear below */
	
} MatchingIdSource_PR;

/* MatchingIdSource */
typedef struct MatchingIdSource {
	MatchingIdSource_PR present;
	union MatchingIdSource_u {
		NULL_t	 none;
		NULL_t	 activationCode;
		OBJECT_IDENTIFIER_t	 smdsOid;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MatchingIdSource_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MatchingIdSource;
extern asn_CHOICE_specifics_t asn_SPC_MatchingIdSource_specs_1;
extern asn_TYPE_member_t asn_MBR_MatchingIdSource_1[3];
extern asn_per_constraints_t asn_PER_type_MatchingIdSource_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MatchingIdSource_H_ */
#include <asn_internal.h>
