/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_MetadataUpdateEnabledProfile_H_
#define	_MetadataUpdateEnabledProfile_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Iccid.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MetadataUpdateEnabledProfile */
typedef struct MetadataUpdateEnabledProfile {
	Iccid_t	*iccid	/* OPTIONAL */;
	OCTET_STRING_t	 tagList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MetadataUpdateEnabledProfile_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MetadataUpdateEnabledProfile;
extern asn_SEQUENCE_specifics_t asn_SPC_MetadataUpdateEnabledProfile_specs_1;
extern asn_TYPE_member_t asn_MBR_MetadataUpdateEnabledProfile_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MetadataUpdateEnabledProfile_H_ */
#include <asn_internal.h>
