/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PermittedEins_H_
#define	_PermittedEins_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PermittedEins */
typedef struct PermittedEins {
	A_SEQUENCE_OF(PrintableString_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PermittedEins_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PermittedEins;

#ifdef __cplusplus
}
#endif

#endif	/* _PermittedEins_H_ */
#include <asn_internal.h>
