/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_PrepareDeviceChangeResponse_H_
#define	_PrepareDeviceChangeResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrepareDeviceChangeResponseOk.h"
#include "PrepareDeviceChangeResponseError.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PrepareDeviceChangeResponse_PR {
	PrepareDeviceChangeResponse_PR_NOTHING,	/* No components present */
	PrepareDeviceChangeResponse_PR_prepareDeviceChangeResponseOk,
	PrepareDeviceChangeResponse_PR_prepareDeviceChangeResponseError
	/* Extensions may appear below */
	
} PrepareDeviceChangeResponse_PR;

/* PrepareDeviceChangeResponse */
typedef struct PrepareDeviceChangeResponse {
	PrepareDeviceChangeResponse_PR present;
	union PrepareDeviceChangeResponse_u {
		PrepareDeviceChangeResponseOk_t	 prepareDeviceChangeResponseOk;
		PrepareDeviceChangeResponseError_t	 prepareDeviceChangeResponseError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrepareDeviceChangeResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrepareDeviceChangeResponse;
extern asn_CHOICE_specifics_t asn_SPC_PrepareDeviceChangeResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_PrepareDeviceChangeResponse_1[2];
extern asn_per_constraints_t asn_PER_type_PrepareDeviceChangeResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PrepareDeviceChangeResponse_H_ */
#include <asn_internal.h>
