/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RpmCommand.h"

static asn_oer_constraints_t asn_OER_type_rpmCommandDetails_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_rpmCommandDetails_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_enable_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__enable, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_enable_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_enable_tag2el_4[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_enable_specs_4 = {
	sizeof(struct RpmCommand__rpmCommandDetails__enable),
	offsetof(struct RpmCommand__rpmCommandDetails__enable, _asn_ctx),
	asn_MAP_enable_tag2el_4,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_enable_4 = {
	"enable",
	"enable",
	&asn_OP_SEQUENCE,
	asn_DEF_enable_tags_4,
	sizeof(asn_DEF_enable_tags_4)
		/sizeof(asn_DEF_enable_tags_4[0]) - 1, /* 1 */
	asn_DEF_enable_tags_4,	/* Same as above */
	sizeof(asn_DEF_enable_tags_4)
		/sizeof(asn_DEF_enable_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_enable_4,
	1,	/* Elements count */
	&asn_SPC_enable_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_disable_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__disable, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_disable_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_disable_tag2el_7[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_disable_specs_7 = {
	sizeof(struct RpmCommand__rpmCommandDetails__disable),
	offsetof(struct RpmCommand__rpmCommandDetails__disable, _asn_ctx),
	asn_MAP_disable_tag2el_7,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_disable_7 = {
	"disable",
	"disable",
	&asn_OP_SEQUENCE,
	asn_DEF_disable_tags_7,
	sizeof(asn_DEF_disable_tags_7)
		/sizeof(asn_DEF_disable_tags_7[0]) - 1, /* 1 */
	asn_DEF_disable_tags_7,	/* Same as above */
	sizeof(asn_DEF_disable_tags_7)
		/sizeof(asn_DEF_disable_tags_7[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_disable_7,
	1,	/* Elements count */
	&asn_SPC_disable_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_delete_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__delete, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_delete_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_delete_tag2el_10[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_delete_specs_10 = {
	sizeof(struct RpmCommand__rpmCommandDetails__delete),
	offsetof(struct RpmCommand__rpmCommandDetails__delete, _asn_ctx),
	asn_MAP_delete_tag2el_10,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_delete_10 = {
	"delete",
	"delete",
	&asn_OP_SEQUENCE,
	asn_DEF_delete_tags_10,
	sizeof(asn_DEF_delete_tags_10)
		/sizeof(asn_DEF_delete_tags_10[0]) - 1, /* 1 */
	asn_DEF_delete_tags_10,	/* Same as above */
	sizeof(asn_DEF_delete_tags_10)
		/sizeof(asn_DEF_delete_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_delete_10,
	1,	/* Elements count */
	&asn_SPC_delete_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_updateMetadata_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__updateMetadata, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__updateMetadata, updateMetadataRequest),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		0,
		&asn_DEF_UpdateMetadataRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"updateMetadataRequest"
		},
};
static const ber_tlv_tag_t asn_DEF_updateMetadata_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_updateMetadata_tag2el_14[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 1, 0, 0 } /* updateMetadataRequest */
};
static asn_SEQUENCE_specifics_t asn_SPC_updateMetadata_specs_14 = {
	sizeof(struct RpmCommand__rpmCommandDetails__updateMetadata),
	offsetof(struct RpmCommand__rpmCommandDetails__updateMetadata, _asn_ctx),
	asn_MAP_updateMetadata_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_updateMetadata_14 = {
	"updateMetadata",
	"updateMetadata",
	&asn_OP_SEQUENCE,
	asn_DEF_updateMetadata_tags_14,
	sizeof(asn_DEF_updateMetadata_tags_14)
		/sizeof(asn_DEF_updateMetadata_tags_14[0]) - 1, /* 1 */
	asn_DEF_updateMetadata_tags_14,	/* Same as above */
	sizeof(asn_DEF_updateMetadata_tags_14)
		/sizeof(asn_DEF_updateMetadata_tags_14[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_updateMetadata_14,
	2,	/* Elements count */
	&asn_SPC_updateMetadata_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_contactPcmp_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails__contactPcmp, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_POINTER, 1, offsetof(struct RpmCommand__rpmCommandDetails__contactPcmp, dpiRpm),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dpiRpm"
		},
};
static const int asn_MAP_contactPcmp_oms_18[] = { 1 };
static const ber_tlv_tag_t asn_DEF_contactPcmp_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_contactPcmp_tag2el_18[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 1, 0, 0 }, /* dpiRpm */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_contactPcmp_specs_18 = {
	sizeof(struct RpmCommand__rpmCommandDetails__contactPcmp),
	offsetof(struct RpmCommand__rpmCommandDetails__contactPcmp, _asn_ctx),
	asn_MAP_contactPcmp_tag2el_18,
	2,	/* Count of tags in the map */
	asn_MAP_contactPcmp_oms_18,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_contactPcmp_18 = {
	"contactPcmp",
	"contactPcmp",
	&asn_OP_SEQUENCE,
	asn_DEF_contactPcmp_tags_18,
	sizeof(asn_DEF_contactPcmp_tags_18)
		/sizeof(asn_DEF_contactPcmp_tags_18[0]) - 1, /* 1 */
	asn_DEF_contactPcmp_tags_18,	/* Same as above */
	sizeof(asn_DEF_contactPcmp_tags_18)
		/sizeof(asn_DEF_contactPcmp_tags_18[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_contactPcmp_18,
	2,	/* Elements count */
	&asn_SPC_contactPcmp_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rpmCommandDetails_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.enable),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_enable_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.disable),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_disable_7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"disable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.Delete),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_delete_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"delete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.listProfileInfo),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ListProfileInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listProfileInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.updateMetadata),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_updateMetadata_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"updateMetadata"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand__rpmCommandDetails, choice.contactPcmp),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_contactPcmp_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactPcmp"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_rpmCommandDetails_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* enable */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* disable */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* delete */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* listProfileInfo */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* updateMetadata */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* contactPcmp */
};
static asn_CHOICE_specifics_t asn_SPC_rpmCommandDetails_specs_3 = {
	sizeof(struct RpmCommand__rpmCommandDetails),
	offsetof(struct RpmCommand__rpmCommandDetails, _asn_ctx),
	offsetof(struct RpmCommand__rpmCommandDetails, present),
	sizeof(((struct RpmCommand__rpmCommandDetails *)0)->present),
	asn_MAP_rpmCommandDetails_tag2el_3,
	6,	/* Count of tags in the map */
	0, 0,
	6	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rpmCommandDetails_3 = {
	"rpmCommandDetails",
	"rpmCommandDetails",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_rpmCommandDetails_constr_3, &asn_PER_type_rpmCommandDetails_constr_3, CHOICE_constraint },
	asn_MBR_rpmCommandDetails_3,
	6,	/* Elements count */
	&asn_SPC_rpmCommandDetails_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RpmCommand_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RpmCommand, continueOnFailure),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"continueOnFailure"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommand, rpmCommandDetails),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_rpmCommandDetails_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmCommandDetails"
		},
};
static const int asn_MAP_RpmCommand_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_RpmCommand_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RpmCommand_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* continueOnFailure */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* enable */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* disable */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* delete */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* listProfileInfo */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* updateMetadata */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 } /* contactPcmp */
};
asn_SEQUENCE_specifics_t asn_SPC_RpmCommand_specs_1 = {
	sizeof(struct RpmCommand),
	offsetof(struct RpmCommand, _asn_ctx),
	asn_MAP_RpmCommand_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_RpmCommand_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RpmCommand = {
	"RpmCommand",
	"RpmCommand",
	&asn_OP_SEQUENCE,
	asn_DEF_RpmCommand_tags_1,
	sizeof(asn_DEF_RpmCommand_tags_1)
		/sizeof(asn_DEF_RpmCommand_tags_1[0]), /* 1 */
	asn_DEF_RpmCommand_tags_1,	/* Same as above */
	sizeof(asn_DEF_RpmCommand_tags_1)
		/sizeof(asn_DEF_RpmCommand_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RpmCommand_1,
	2,	/* Elements count */
	&asn_SPC_RpmCommand_specs_1	/* Additional specs */
};

