/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RpmConfiguration.h"

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmConfiguration__managingDpList__Member, managingDpOid),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"managingDpOid"
		},
	{ ATF_POINTER, 2, offsetof(struct RpmConfiguration__managingDpList__Member, rpmType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RpmType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmType"
		},
	{ ATF_POINTER, 1, offsetof(struct RpmConfiguration__managingDpList__Member, tagList),
		(ASN_TAG_CLASS_APPLICATION | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tagList"
		},
};
static const int asn_MAP_Member_oms_3[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_APPLICATION | (28 << 2)), 2, 0, 0 }, /* tagList */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* managingDpOid */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rpmType */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct RpmConfiguration__managingDpList__Member),
	offsetof(struct RpmConfiguration__managingDpList__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	3,	/* Count of tags in the map */
	asn_MAP_Member_oms_3,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	3,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_managingDpList_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_managingDpList_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_managingDpList_specs_2 = {
	sizeof(struct RpmConfiguration__managingDpList),
	offsetof(struct RpmConfiguration__managingDpList, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_managingDpList_2 = {
	"managingDpList",
	"managingDpList",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_managingDpList_tags_2,
	sizeof(asn_DEF_managingDpList_tags_2)
		/sizeof(asn_DEF_managingDpList_tags_2[0]) - 1, /* 1 */
	asn_DEF_managingDpList_tags_2,	/* Same as above */
	sizeof(asn_DEF_managingDpList_tags_2)
		/sizeof(asn_DEF_managingDpList_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_managingDpList_2,
	1,	/* Single element */
	&asn_SPC_managingDpList_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RpmConfiguration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmConfiguration, managingDpList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_managingDpList_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"managingDpList"
		},
	{ ATF_POINTER, 2, offsetof(struct RpmConfiguration, pollingAddress),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pollingAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct RpmConfiguration, allowedCiPKId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"allowedCiPKId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmConfiguration, profileOwnerOid),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwnerOid"
		},
};
static const int asn_MAP_RpmConfiguration_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RpmConfiguration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RpmConfiguration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* managingDpList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pollingAddress */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* allowedCiPKId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* profileOwnerOid */
};
asn_SEQUENCE_specifics_t asn_SPC_RpmConfiguration_specs_1 = {
	sizeof(struct RpmConfiguration),
	offsetof(struct RpmConfiguration, _asn_ctx),
	asn_MAP_RpmConfiguration_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RpmConfiguration_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RpmConfiguration = {
	"RpmConfiguration",
	"RpmConfiguration",
	&asn_OP_SEQUENCE,
	asn_DEF_RpmConfiguration_tags_1,
	sizeof(asn_DEF_RpmConfiguration_tags_1)
		/sizeof(asn_DEF_RpmConfiguration_tags_1[0]), /* 1 */
	asn_DEF_RpmConfiguration_tags_1,	/* Same as above */
	sizeof(asn_DEF_RpmConfiguration_tags_1)
		/sizeof(asn_DEF_RpmConfiguration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RpmConfiguration_1,
	4,	/* Elements count */
	&asn_SPC_RpmConfiguration_specs_1	/* Additional specs */
};

