/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RpmCommandResult_H_
#define	_RpmCommandResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Iccid.h"
#include "EnableProfileResponse.h"
#include "DisableProfileResponse.h"
#include "DeleteProfileResponse.h"
#include "ProfileInfoListResponse.h"
#include "UpdateMetadataResponse.h"
#include "ContactPcmpResponse.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RpmCommandResult__rpmCommandResultData_PR {
	RpmCommandResult__rpmCommandResultData_PR_NOTHING,	/* No components present */
	RpmCommandResult__rpmCommandResultData_PR_enableResult,
	RpmCommandResult__rpmCommandResultData_PR_disableResult,
	RpmCommandResult__rpmCommandResultData_PR_deleteResult,
	RpmCommandResult__rpmCommandResultData_PR_listProfileInfoResult,
	RpmCommandResult__rpmCommandResultData_PR_updateMetadataResult,
	RpmCommandResult__rpmCommandResultData_PR_contactPcmpResult,
	RpmCommandResult__rpmCommandResultData_PR_rpmProcessingTerminated
	/* Extensions may appear below */
	
} RpmCommandResult__rpmCommandResultData_PR;
typedef enum RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated {
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_resultSizeOverflow	= 1,
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_unknownOrDamagedCommand	= 2,
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_interruption	= 3,
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_commandsWithRefreshExceeded	= 4,
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_commandAfterContactPcmp	= 5,
	RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated_commandPackageTooLarge	= 6
} e_RpmCommandResult__rpmCommandResultData__rpmProcessingTerminated;

/* RpmCommandResult */
typedef struct RpmCommandResult {
	Iccid_t	*iccid	/* OPTIONAL */;
	struct RpmCommandResult__rpmCommandResultData {
		RpmCommandResult__rpmCommandResultData_PR present;
		union RpmCommandResult__rpmCommandResultData_u {
			EnableProfileResponse_t	 enableResult;
			DisableProfileResponse_t	 disableResult;
			DeleteProfileResponse_t	 deleteResult;
			ProfileInfoListResponse_t	 listProfileInfoResult;
			UpdateMetadataResponse_t	 updateMetadataResult;
			ContactPcmpResponse_t	 contactPcmpResult;
			long	 rpmProcessingTerminated;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rpmCommandResultData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RpmCommandResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RpmCommandResult;
extern asn_SEQUENCE_specifics_t asn_SPC_RpmCommandResult_specs_1;
extern asn_TYPE_member_t asn_MBR_RpmCommandResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RpmCommandResult_H_ */
#include <asn_internal.h>
