/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "RpmCommandResult.h"

static asn_oer_constraints_t asn_OER_type_rpmCommandResultData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_rpmCommandResultData_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  6 }	/* (0..6,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_rpmCommandResultData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.enableResult),
		(ASN_TAG_CLASS_CONTEXT | (49 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EnableProfileResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enableResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.disableResult),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DisableProfileResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"disableResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.deleteResult),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DeleteProfileResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deleteResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.listProfileInfoResult),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileInfoListResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listProfileInfoResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.updateMetadataResult),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UpdateMetadataResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"updateMetadataResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.contactPcmpResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ContactPcmpResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactPcmpResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult__rpmCommandResultData, choice.rpmProcessingTerminated),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmProcessingTerminated"
		},
};
static const unsigned asn_MAP_rpmCommandResultData_to_canonical_3[] = { 6, 5, 4, 3, 0, 1, 2 };
static const unsigned asn_MAP_rpmCommandResultData_from_canonical_3[] = { 4, 5, 6, 3, 2, 1, 0 };
static const asn_TYPE_tag2member_t asn_MAP_rpmCommandResultData_tag2el_3[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, 0, 0 }, /* rpmProcessingTerminated */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 5, 0, 0 }, /* contactPcmpResult */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 4, 0, 0 }, /* updateMetadataResult */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 3, 0, 0 }, /* listProfileInfoResult */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 0, 0, 0 }, /* enableResult */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 1, 0, 0 }, /* disableResult */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 2, 0, 0 } /* deleteResult */
};
static asn_CHOICE_specifics_t asn_SPC_rpmCommandResultData_specs_3 = {
	sizeof(struct RpmCommandResult__rpmCommandResultData),
	offsetof(struct RpmCommandResult__rpmCommandResultData, _asn_ctx),
	offsetof(struct RpmCommandResult__rpmCommandResultData, present),
	sizeof(((struct RpmCommandResult__rpmCommandResultData *)0)->present),
	asn_MAP_rpmCommandResultData_tag2el_3,
	7,	/* Count of tags in the map */
	asn_MAP_rpmCommandResultData_to_canonical_3,
	asn_MAP_rpmCommandResultData_from_canonical_3,
	7	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rpmCommandResultData_3 = {
	"rpmCommandResultData",
	"rpmCommandResultData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_rpmCommandResultData_constr_3, &asn_PER_type_rpmCommandResultData_constr_3, CHOICE_constraint },
	asn_MBR_rpmCommandResultData_3,
	7,	/* Elements count */
	&asn_SPC_rpmCommandResultData_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RpmCommandResult_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RpmCommandResult, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RpmCommandResult, rpmCommandResultData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_rpmCommandResultData_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rpmCommandResultData"
		},
};
static const int asn_MAP_RpmCommandResult_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_RpmCommandResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RpmCommandResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* rpmProcessingTerminated */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* contactPcmpResult */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 1, 0, 0 }, /* updateMetadataResult */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 1, 0, 0 }, /* listProfileInfoResult */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 1, 0, 0 }, /* enableResult */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 1, 0, 0 }, /* disableResult */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 1, 0, 0 } /* deleteResult */
};
asn_SEQUENCE_specifics_t asn_SPC_RpmCommandResult_specs_1 = {
	sizeof(struct RpmCommandResult),
	offsetof(struct RpmCommandResult, _asn_ctx),
	asn_MAP_RpmCommandResult_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_RpmCommandResult_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RpmCommandResult = {
	"RpmCommandResult",
	"RpmCommandResult",
	&asn_OP_SEQUENCE,
	asn_DEF_RpmCommandResult_tags_1,
	sizeof(asn_DEF_RpmCommandResult_tags_1)
		/sizeof(asn_DEF_RpmCommandResult_tags_1[0]), /* 1 */
	asn_DEF_RpmCommandResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_RpmCommandResult_tags_1)
		/sizeof(asn_DEF_RpmCommandResult_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RpmCommandResult_1,
	2,	/* Elements count */
	&asn_SPC_RpmCommandResult_specs_1	/* Additional specs */
};

