/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RpmCommand_H_
#define	_RpmCommand_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "ListProfileInfo.h"
#include "Iccid.h"
#include <constr_SEQUENCE.h>
#include "UpdateMetadataRequest.h"
#include <UTF8String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RpmCommand__rpmCommandDetails_PR {
	RpmCommand__rpmCommandDetails_PR_NOTHING,	/* No components present */
	RpmCommand__rpmCommandDetails_PR_enable,
	RpmCommand__rpmCommandDetails_PR_disable,
	RpmCommand__rpmCommandDetails_PR_delete,
	RpmCommand__rpmCommandDetails_PR_listProfileInfo,
	RpmCommand__rpmCommandDetails_PR_updateMetadata,
	RpmCommand__rpmCommandDetails_PR_contactPcmp
	/* Extensions may appear below */
	
} RpmCommand__rpmCommandDetails_PR;

/* RpmCommand */
typedef struct RpmCommand {
	NULL_t	*continueOnFailure	/* OPTIONAL */;
	struct RpmCommand__rpmCommandDetails {
		RpmCommand__rpmCommandDetails_PR present;
		union RpmCommand__rpmCommandDetails_u {
			struct RpmCommand__rpmCommandDetails__enable {
				Iccid_t	 iccid;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} enable;
			struct RpmCommand__rpmCommandDetails__disable {
				Iccid_t	 iccid;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} disable;
			struct RpmCommand__rpmCommandDetails__delete {
				Iccid_t	 iccid;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} Delete;
			ListProfileInfo_t	 listProfileInfo;
			struct RpmCommand__rpmCommandDetails__updateMetadata {
				Iccid_t	 iccid;
				UpdateMetadataRequest_t	 updateMetadataRequest;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} updateMetadata;
			struct RpmCommand__rpmCommandDetails__contactPcmp {
				Iccid_t	 iccid;
				UTF8String_t	*dpiRpm	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} contactPcmp;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rpmCommandDetails;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RpmCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RpmCommand;
extern asn_SEQUENCE_specifics_t asn_SPC_RpmCommand_specs_1;
extern asn_TYPE_member_t asn_MBR_RpmCommand_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RpmCommand_H_ */
#include <asn_internal.h>
