/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RpmConfiguration_H_
#define	_RpmConfiguration_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "SubjectKeyIdentifier.h"
#include <OBJECT_IDENTIFIER.h>
#include <asn_SEQUENCE_OF.h>
#include "RpmType.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct RpmConfiguration__managingDpList__Member {
	OBJECT_IDENTIFIER_t	 managingDpOid;
	RpmType_t	*rpmType	/* OPTIONAL */;
	OCTET_STRING_t	*tagList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RpmConfiguration__managingDpList__Member;

/* RpmConfiguration */
typedef struct RpmConfiguration {
	struct RpmConfiguration__managingDpList {
		A_SEQUENCE_OF(RpmConfiguration__managingDpList__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} managingDpList;
	UTF8String_t	*pollingAddress	/* OPTIONAL */;
	SubjectKeyIdentifier_t	*allowedCiPKId	/* OPTIONAL */;
	OBJECT_IDENTIFIER_t	 profileOwnerOid;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RpmConfiguration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RpmConfiguration;
extern asn_SEQUENCE_specifics_t asn_SPC_RpmConfiguration_specs_1;
extern asn_TYPE_member_t asn_MBR_RpmConfiguration_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RpmConfiguration_H_ */
#include <asn_internal.h>
