/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_RpmType_H_
#define	_RpmType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RpmType {
	RpmType_enable	= 0,
	RpmType_disable	= 1,
	RpmType_delete	= 2,
	RpmType_listProfileInfo	= 3,
	RpmType_contactPcmp	= 4
} e_RpmType;

/* RpmType */
typedef BIT_STRING_t	 RpmType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RpmType;
asn_struct_free_f RpmType_free;
asn_struct_print_f RpmType_print;
asn_constr_check_f RpmType_constraint;
ber_type_decoder_f RpmType_decode_ber;
der_type_encoder_f RpmType_encode_der;
xer_type_decoder_f RpmType_decode_xer;
xer_type_encoder_f RpmType_encode_xer;
oer_type_decoder_f RpmType_decode_oer;
oer_type_encoder_f RpmType_encode_oer;
per_type_decoder_f RpmType_decode_uper;
per_type_encoder_f RpmType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RpmType_H_ */
#include <asn_internal.h>
