/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ServiceDescription_H_
#define	_ServiceDescription_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceDescription {
	ServiceDescription_voice	= 0,
	ServiceDescription_data	= 1
} e_ServiceDescription;

/* ServiceDescription */
typedef BIT_STRING_t	 ServiceDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceDescription;
asn_struct_free_f ServiceDescription_free;
asn_struct_print_f ServiceDescription_print;
asn_constr_check_f ServiceDescription_constraint;
ber_type_decoder_f ServiceDescription_decode_ber;
der_type_encoder_f ServiceDescription_encode_der;
xer_type_decoder_f ServiceDescription_decode_xer;
xer_type_encoder_f ServiceDescription_encode_xer;
oer_type_decoder_f ServiceDescription_decode_oer;
oer_type_encoder_f ServiceDescription_encode_oer;
per_type_decoder_f ServiceDescription_decode_uper;
per_type_encoder_f ServiceDescription_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceDescription_H_ */
#include <asn_internal.h>
