/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ServerWithPendingOperation_H_
#define	_ServerWithPendingOperation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <UTF8String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServerWithPendingOperation_PR {
	ServerWithPendingOperation_PR_NOTHING,	/* No components present */
	ServerWithPendingOperation_PR_pollingAddress,
	ServerWithPendingOperation_PR_rootSmds,
	ServerWithPendingOperation_PR_defaultSmdp,
	ServerWithPendingOperation_PR_explicitAddress
	/* Extensions may appear below */
	
} ServerWithPendingOperation_PR;

/* ServerWithPendingOperation */
typedef struct ServerWithPendingOperation {
	ServerWithPendingOperation_PR present;
	union ServerWithPendingOperation_u {
		NULL_t	 pollingAddress;
		NULL_t	 rootSmds;
		NULL_t	 defaultSmdp;
		UTF8String_t	 explicitAddress;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServerWithPendingOperation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServerWithPendingOperation;
extern asn_CHOICE_specifics_t asn_SPC_ServerWithPendingOperation_specs_1;
extern asn_TYPE_member_t asn_MBR_ServerWithPendingOperation_1[4];
extern asn_per_constraints_t asn_PER_type_ServerWithPendingOperation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ServerWithPendingOperation_H_ */
#include <asn_internal.h>
