/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_ServerRspCapability_H_
#define	_ServerRspCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServerRspCapability {
	ServerRspCapability_crlStaplingV3Support	= 0,
	ServerRspCapability_eventListSigningV3Support	= 1,
	ServerRspCapability_pushServiceV3Support	= 2,
	ServerRspCapability_cancelForEmptySpnPnSupport	= 3,
	ServerRspCapability_cancelForSessionAbortedSupport	= 4
} e_ServerRspCapability;

/* ServerRspCapability */
typedef BIT_STRING_t	 ServerRspCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServerRspCapability;
asn_struct_free_f ServerRspCapability_free;
asn_struct_print_f ServerRspCapability_print;
asn_constr_check_f ServerRspCapability_constraint;
ber_type_decoder_f ServerRspCapability_decode_ber;
der_type_encoder_f ServerRspCapability_encode_der;
xer_type_decoder_f ServerRspCapability_decode_xer;
xer_type_encoder_f ServerRspCapability_encode_xer;
oer_type_decoder_f ServerRspCapability_decode_oer;
oer_type_encoder_f ServerRspCapability_encode_oer;
per_type_decoder_f ServerRspCapability_decode_uper;
per_type_encoder_f ServerRspCapability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServerRspCapability_H_ */
#include <asn_internal.h>
