/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "ServerWithPendingOperation.h"

static asn_oer_constraints_t asn_OER_type_ServerWithPendingOperation_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ServerWithPendingOperation_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ServerWithPendingOperation_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServerWithPendingOperation, choice.pollingAddress),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pollingAddress"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServerWithPendingOperation, choice.rootSmds),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rootSmds"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServerWithPendingOperation, choice.defaultSmdp),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultSmdp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServerWithPendingOperation, choice.explicitAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"explicitAddress"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ServerWithPendingOperation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pollingAddress */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rootSmds */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* defaultSmdp */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* explicitAddress */
};
asn_CHOICE_specifics_t asn_SPC_ServerWithPendingOperation_specs_1 = {
	sizeof(struct ServerWithPendingOperation),
	offsetof(struct ServerWithPendingOperation, _asn_ctx),
	offsetof(struct ServerWithPendingOperation, present),
	sizeof(((struct ServerWithPendingOperation *)0)->present),
	asn_MAP_ServerWithPendingOperation_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ServerWithPendingOperation = {
	"ServerWithPendingOperation",
	"ServerWithPendingOperation",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ServerWithPendingOperation_constr_1, &asn_PER_type_ServerWithPendingOperation_constr_1, CHOICE_constraint },
	asn_MBR_ServerWithPendingOperation_1,
	4,	/* Elements count */
	&asn_SPC_ServerWithPendingOperation_specs_1	/* Additional specs */
};

