/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SessionContext_H_
#define	_SessionContext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VersionType.h"
#include <BOOLEAN.h>
#include "SubjectKeyIdentifier.h"
#include <OBJECT_IDENTIFIER.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SessionContext */
typedef struct SessionContext {
	VersionType_t	 serverSvn;
	BOOLEAN_t	 crlStaplingV3Used;
	SubjectKeyIdentifier_t	*euiccCiPKIdToBeUsedV3	/* OPTIONAL */;
	struct SessionContext__supportedPushServices {
		A_SEQUENCE_OF(OBJECT_IDENTIFIER_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *supportedPushServices;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SessionContext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SessionContext;
extern asn_SEQUENCE_specifics_t asn_SPC_SessionContext_specs_1;
extern asn_TYPE_member_t asn_MBR_SessionContext_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SessionContext_H_ */
#include <asn_internal.h>
