/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SessionContext.h"

static asn_TYPE_member_t asn_MBR_supportedPushServices_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_supportedPushServices_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_supportedPushServices_specs_5 = {
	sizeof(struct SessionContext__supportedPushServices),
	offsetof(struct SessionContext__supportedPushServices, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_supportedPushServices_5 = {
	"supportedPushServices",
	"supportedPushServices",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_supportedPushServices_tags_5,
	sizeof(asn_DEF_supportedPushServices_tags_5)
		/sizeof(asn_DEF_supportedPushServices_tags_5[0]) - 1, /* 1 */
	asn_DEF_supportedPushServices_tags_5,	/* Same as above */
	sizeof(asn_DEF_supportedPushServices_tags_5)
		/sizeof(asn_DEF_supportedPushServices_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_supportedPushServices_5,
	1,	/* Single element */
	&asn_SPC_supportedPushServices_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SessionContext_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SessionContext, serverSvn),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VersionType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverSvn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionContext, crlStaplingV3Used),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"crlStaplingV3Used"
		},
	{ ATF_POINTER, 2, offsetof(struct SessionContext, euiccCiPKIdToBeUsedV3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKIdToBeUsedV3"
		},
	{ ATF_POINTER, 1, offsetof(struct SessionContext, supportedPushServices),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_supportedPushServices_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedPushServices"
		},
};
static const int asn_MAP_SessionContext_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_SessionContext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SessionContext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* serverSvn */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* crlStaplingV3Used */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* euiccCiPKIdToBeUsedV3 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* supportedPushServices */
};
asn_SEQUENCE_specifics_t asn_SPC_SessionContext_specs_1 = {
	sizeof(struct SessionContext),
	offsetof(struct SessionContext, _asn_ctx),
	asn_MAP_SessionContext_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SessionContext_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SessionContext = {
	"SessionContext",
	"SessionContext",
	&asn_OP_SEQUENCE,
	asn_DEF_SessionContext_tags_1,
	sizeof(asn_DEF_SessionContext_tags_1)
		/sizeof(asn_DEF_SessionContext_tags_1[0]), /* 1 */
	asn_DEF_SessionContext_tags_1,	/* Same as above */
	sizeof(asn_DEF_SessionContext_tags_1)
		/sizeof(asn_DEF_SessionContext_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SessionContext_1,
	4,	/* Elements count */
	&asn_SPC_SessionContext_specs_1	/* Additional specs */
};

