/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SGP32-CancelSessionResponse.h"

static asn_oer_constraints_t asn_OER_type_SGP32_CancelSessionResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SGP32_CancelSessionResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_SGP32_CancelSessionResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_CancelSessionResponse, choice.cancelSessionResponseOk),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionResponseOk,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseOk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_CancelSessionResponse, choice.cancelSessionResponseError),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseError"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_CancelSessionResponse, choice.compactCancelSessionResponseOk),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompactCancelSessionResponseOk,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compactCancelSessionResponseOk"
		},
};
static const ber_tlv_tag_t asn_DEF_SGP32_CancelSessionResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (65 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SGP32_CancelSessionResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cancelSessionResponseOk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cancelSessionResponseError */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* compactCancelSessionResponseOk */
};
asn_CHOICE_specifics_t asn_SPC_SGP32_CancelSessionResponse_specs_1 = {
	sizeof(struct SGP32_CancelSessionResponse),
	offsetof(struct SGP32_CancelSessionResponse, _asn_ctx),
	offsetof(struct SGP32_CancelSessionResponse, present),
	sizeof(((struct SGP32_CancelSessionResponse *)0)->present),
	asn_MAP_SGP32_CancelSessionResponse_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SGP32_CancelSessionResponse = {
	"SGP32-CancelSessionResponse",
	"SGP32-CancelSessionResponse",
	&asn_OP_CHOICE,
	asn_DEF_SGP32_CancelSessionResponse_tags_1,
	sizeof(asn_DEF_SGP32_CancelSessionResponse_tags_1)
		/sizeof(asn_DEF_SGP32_CancelSessionResponse_tags_1[0]), /* 1 */
	asn_DEF_SGP32_CancelSessionResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_SGP32_CancelSessionResponse_tags_1)
		/sizeof(asn_DEF_SGP32_CancelSessionResponse_tags_1[0]), /* 1 */
	{ &asn_OER_type_SGP32_CancelSessionResponse_constr_1, &asn_PER_type_SGP32_CancelSessionResponse_constr_1, CHOICE_constraint },
	asn_MBR_SGP32_CancelSessionResponse_1,
	3,	/* Elements count */
	&asn_SPC_SGP32_CancelSessionResponse_specs_1	/* Additional specs */
};

