/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SmdpSigned6.h"

static int
memb_dcSessionId_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 16)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_dcSessionId_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..16)) */};
static asn_per_constraints_t asn_PER_memb_dcSessionId_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  1,  16 }	/* (SIZE(1..16)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_requestSpecificData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_requestSpecificData_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_retryData_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned6__requestSpecificData__retryData, retryDelay),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"retryDelay"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned6__requestSpecificData__retryData, dcSessionId),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_dcSessionId_constr_6, &asn_PER_memb_dcSessionId_constr_6,  memb_dcSessionId_constraint_4 },
		0, 0, /* No default value */
		"dcSessionId"
		},
};
static const ber_tlv_tag_t asn_DEF_retryData_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_retryData_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* retryDelay */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dcSessionId */
};
static asn_SEQUENCE_specifics_t asn_SPC_retryData_specs_4 = {
	sizeof(struct SmdpSigned6__requestSpecificData__retryData),
	offsetof(struct SmdpSigned6__requestSpecificData__retryData, _asn_ctx),
	asn_MAP_retryData_tag2el_4,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_retryData_4 = {
	"retryData",
	"retryData",
	&asn_OP_SEQUENCE,
	asn_DEF_retryData_tags_4,
	sizeof(asn_DEF_retryData_tags_4)
		/sizeof(asn_DEF_retryData_tags_4[0]) - 1, /* 1 */
	asn_DEF_retryData_tags_4,	/* Same as above */
	sizeof(asn_DEF_retryData_tags_4)
		/sizeof(asn_DEF_retryData_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_retryData_4,
	2,	/* Elements count */
	&asn_SPC_retryData_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_requestSpecificData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned6__requestSpecificData, choice.retryData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_retryData_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"retryData"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_requestSpecificData_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* retryData */
};
static asn_CHOICE_specifics_t asn_SPC_requestSpecificData_specs_3 = {
	sizeof(struct SmdpSigned6__requestSpecificData),
	offsetof(struct SmdpSigned6__requestSpecificData, _asn_ctx),
	offsetof(struct SmdpSigned6__requestSpecificData, present),
	sizeof(((struct SmdpSigned6__requestSpecificData *)0)->present),
	asn_MAP_requestSpecificData_tag2el_3,
	1,	/* Count of tags in the map */
	0, 0,
	1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requestSpecificData_3 = {
	"requestSpecificData",
	"requestSpecificData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_requestSpecificData_constr_3, &asn_PER_type_requestSpecificData_constr_3, CHOICE_constraint },
	asn_MBR_requestSpecificData_3,
	1,	/* Elements count */
	&asn_SPC_requestSpecificData_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SmdpSigned6_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned6, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned6, requestSpecificData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_requestSpecificData_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestSpecificData"
		},
};
static const ber_tlv_tag_t asn_DEF_SmdpSigned6_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SmdpSigned6_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 } /* retryData */
};
asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned6_specs_1 = {
	sizeof(struct SmdpSigned6),
	offsetof(struct SmdpSigned6, _asn_ctx),
	asn_MAP_SmdpSigned6_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SmdpSigned6 = {
	"SmdpSigned6",
	"SmdpSigned6",
	&asn_OP_SEQUENCE,
	asn_DEF_SmdpSigned6_tags_1,
	sizeof(asn_DEF_SmdpSigned6_tags_1)
		/sizeof(asn_DEF_SmdpSigned6_tags_1[0]), /* 1 */
	asn_DEF_SmdpSigned6_tags_1,	/* Same as above */
	sizeof(asn_DEF_SmdpSigned6_tags_1)
		/sizeof(asn_DEF_SmdpSigned6_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SmdpSigned6_1,
	2,	/* Elements count */
	&asn_SPC_SmdpSigned6_specs_1	/* Additional specs */
};

