/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SmdpSigned6_H_
#define	_SmdpSigned6_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SmdpSigned6__requestSpecificData_PR {
	SmdpSigned6__requestSpecificData_PR_NOTHING,	/* No components present */
	SmdpSigned6__requestSpecificData_PR_retryData
	/* Extensions may appear below */
	
} SmdpSigned6__requestSpecificData_PR;

/* SmdpSigned6 */
typedef struct SmdpSigned6 {
	TransactionId_t	 transactionId;
	struct SmdpSigned6__requestSpecificData {
		SmdpSigned6__requestSpecificData_PR present;
		union SmdpSigned6__requestSpecificData_u {
			struct SmdpSigned6__requestSpecificData__retryData {
				long	 retryDelay;
				OCTET_STRING_t	 dcSessionId;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} retryData;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} requestSpecificData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SmdpSigned6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmdpSigned6;
extern asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned6_specs_1;
extern asn_TYPE_member_t asn_MBR_SmdpSigned6_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SmdpSigned6_H_ */
#include <asn_internal.h>
