/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SmdpSigned4_H_
#define	_SmdpSigned4_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include <BOOLEAN.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SmdpSigned4 */
typedef struct SmdpSigned4 {
	TransactionId_t	 transactionId;
	BOOLEAN_t	 ccRequiredFlag;
	UTF8String_t	*activationCodeForProfileRecovery	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SmdpSigned4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmdpSigned4;
extern asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned4_specs_1;
extern asn_TYPE_member_t asn_MBR_SmdpSigned4_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SmdpSigned4_H_ */
#include <asn_internal.h>
