/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SmdpSigned5_H_
#define	_SmdpSigned5_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "DeviceChangeResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SmdpSigned5 */
typedef struct SmdpSigned5 {
	TransactionId_t	 transactionId;
	DeviceChangeResponse_t	 deviceChangeResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SmdpSigned5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmdpSigned5;
extern asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned5_specs_1;
extern asn_TYPE_member_t asn_MBR_SmdpSigned5_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SmdpSigned5_H_ */
#include <asn_internal.h>
