/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SmdpSigned5.h"

asn_TYPE_member_t asn_MBR_SmdpSigned5_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned5, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdpSigned5, deviceChangeResponse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_DeviceChangeResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"deviceChangeResponse"
		},
};
static const ber_tlv_tag_t asn_DEF_SmdpSigned5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SmdpSigned5_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* deviceChangeResponse */
};
asn_SEQUENCE_specifics_t asn_SPC_SmdpSigned5_specs_1 = {
	sizeof(struct SmdpSigned5),
	offsetof(struct SmdpSigned5, _asn_ctx),
	asn_MAP_SmdpSigned5_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SmdpSigned5 = {
	"SmdpSigned5",
	"SmdpSigned5",
	&asn_OP_SEQUENCE,
	asn_DEF_SmdpSigned5_tags_1,
	sizeof(asn_DEF_SmdpSigned5_tags_1)
		/sizeof(asn_DEF_SmdpSigned5_tags_1[0]), /* 1 */
	asn_DEF_SmdpSigned5_tags_1,	/* Same as above */
	sizeof(asn_DEF_SmdpSigned5_tags_1)
		/sizeof(asn_DEF_SmdpSigned5_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SmdpSigned5_1,
	2,	/* Elements count */
	&asn_SPC_SmdpSigned5_specs_1	/* Additional specs */
};

