/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "SmdsSigned2.h"

static int
memb_ecId_constraint_4(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 16 && size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_ecId_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(16..32)) */};
static asn_per_constraints_t asn_PER_memb_ecId_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  16,  32 }	/* (SIZE(16..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_requestSpecificData_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_requestSpecificData_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_eventEntries_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EventRecordV3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_eventEntries_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_eventEntries_specs_5 = {
	sizeof(struct SmdsSigned2__requestSpecificData__eventList__eventEntries),
	offsetof(struct SmdsSigned2__requestSpecificData__eventList__eventEntries, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventEntries_5 = {
	"eventEntries",
	"eventEntries",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_eventEntries_tags_5,
	sizeof(asn_DEF_eventEntries_tags_5)
		/sizeof(asn_DEF_eventEntries_tags_5[0]) - 1, /* 1 */
	asn_DEF_eventEntries_tags_5,	/* Same as above */
	sizeof(asn_DEF_eventEntries_tags_5)
		/sizeof(asn_DEF_eventEntries_tags_5[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_eventEntries_5,
	1,	/* Single element */
	&asn_SPC_eventEntries_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventList_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdsSigned2__requestSpecificData__eventList, eventEntries),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventEntries_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventEntries"
		},
	{ ATF_POINTER, 2, offsetof(struct SmdsSigned2__requestSpecificData__eventList, ecId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_ecId_constr_7, &asn_PER_memb_ecId_constr_7,  memb_ecId_constraint_4 },
		0, 0, /* No default value */
		"ecId"
		},
	{ ATF_POINTER, 1, offsetof(struct SmdsSigned2__requestSpecificData__eventList, pushServiceRefreshTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pushServiceRefreshTime"
		},
};
static const int asn_MAP_eventList_oms_4[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_eventList_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_eventList_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* eventEntries */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ecId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 } /* pushServiceRefreshTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventList_specs_4 = {
	sizeof(struct SmdsSigned2__requestSpecificData__eventList),
	offsetof(struct SmdsSigned2__requestSpecificData__eventList, _asn_ctx),
	asn_MAP_eventList_tag2el_4,
	3,	/* Count of tags in the map */
	asn_MAP_eventList_oms_4,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventList_4 = {
	"eventList",
	"eventList",
	&asn_OP_SEQUENCE,
	asn_DEF_eventList_tags_4,
	sizeof(asn_DEF_eventList_tags_4)
		/sizeof(asn_DEF_eventList_tags_4[0]) - 1, /* 1 */
	asn_DEF_eventList_tags_4,	/* Same as above */
	sizeof(asn_DEF_eventList_tags_4)
		/sizeof(asn_DEF_eventList_tags_4[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_eventList_4,
	3,	/* Elements count */
	&asn_SPC_eventList_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pushServiceRegistrationResult_10[] = {
	{ ATF_POINTER, 1, offsetof(struct SmdsSigned2__requestSpecificData__pushServiceRegistrationResult, pushServiceRefreshTime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GeneralizedTime,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pushServiceRefreshTime"
		},
};
static const int asn_MAP_pushServiceRegistrationResult_oms_10[] = { 0 };
static const ber_tlv_tag_t asn_DEF_pushServiceRegistrationResult_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_pushServiceRegistrationResult_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* pushServiceRefreshTime */
};
static asn_SEQUENCE_specifics_t asn_SPC_pushServiceRegistrationResult_specs_10 = {
	sizeof(struct SmdsSigned2__requestSpecificData__pushServiceRegistrationResult),
	offsetof(struct SmdsSigned2__requestSpecificData__pushServiceRegistrationResult, _asn_ctx),
	asn_MAP_pushServiceRegistrationResult_tag2el_10,
	1,	/* Count of tags in the map */
	asn_MAP_pushServiceRegistrationResult_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pushServiceRegistrationResult_10 = {
	"pushServiceRegistrationResult",
	"pushServiceRegistrationResult",
	&asn_OP_SEQUENCE,
	asn_DEF_pushServiceRegistrationResult_tags_10,
	sizeof(asn_DEF_pushServiceRegistrationResult_tags_10)
		/sizeof(asn_DEF_pushServiceRegistrationResult_tags_10[0]) - 1, /* 1 */
	asn_DEF_pushServiceRegistrationResult_tags_10,	/* Same as above */
	sizeof(asn_DEF_pushServiceRegistrationResult_tags_10)
		/sizeof(asn_DEF_pushServiceRegistrationResult_tags_10[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_pushServiceRegistrationResult_10,
	1,	/* Elements count */
	&asn_SPC_pushServiceRegistrationResult_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_requestSpecificData_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdsSigned2__requestSpecificData, choice.eventList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_eventList_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventList"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdsSigned2__requestSpecificData, choice.pushServiceRegistrationResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_pushServiceRegistrationResult_10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pushServiceRegistrationResult"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_requestSpecificData_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pushServiceRegistrationResult */
};
static asn_CHOICE_specifics_t asn_SPC_requestSpecificData_specs_3 = {
	sizeof(struct SmdsSigned2__requestSpecificData),
	offsetof(struct SmdsSigned2__requestSpecificData, _asn_ctx),
	offsetof(struct SmdsSigned2__requestSpecificData, present),
	sizeof(((struct SmdsSigned2__requestSpecificData *)0)->present),
	asn_MAP_requestSpecificData_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_requestSpecificData_3 = {
	"requestSpecificData",
	"requestSpecificData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_requestSpecificData_constr_3, &asn_PER_type_requestSpecificData_constr_3, CHOICE_constraint },
	asn_MBR_requestSpecificData_3,
	2,	/* Elements count */
	&asn_SPC_requestSpecificData_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SmdsSigned2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SmdsSigned2, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SmdsSigned2, requestSpecificData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_requestSpecificData_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"requestSpecificData"
		},
};
static const ber_tlv_tag_t asn_DEF_SmdsSigned2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SmdsSigned2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, -1, 0 }, /* eventList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pushServiceRegistrationResult */
};
asn_SEQUENCE_specifics_t asn_SPC_SmdsSigned2_specs_1 = {
	sizeof(struct SmdsSigned2),
	offsetof(struct SmdsSigned2, _asn_ctx),
	asn_MAP_SmdsSigned2_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SmdsSigned2 = {
	"SmdsSigned2",
	"SmdsSigned2",
	&asn_OP_SEQUENCE,
	asn_DEF_SmdsSigned2_tags_1,
	sizeof(asn_DEF_SmdsSigned2_tags_1)
		/sizeof(asn_DEF_SmdsSigned2_tags_1[0]), /* 1 */
	asn_DEF_SmdsSigned2_tags_1,	/* Same as above */
	sizeof(asn_DEF_SmdsSigned2_tags_1)
		/sizeof(asn_DEF_SmdsSigned2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SmdsSigned2_1,
	2,	/* Elements count */
	&asn_SPC_SmdsSigned2_specs_1	/* Additional specs */
};

