/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SmdsSigned2_H_
#define	_SmdsSigned2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include <OCTET_STRING.h>
#include <GeneralizedTime.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SmdsSigned2__requestSpecificData_PR {
	SmdsSigned2__requestSpecificData_PR_NOTHING,	/* No components present */
	SmdsSigned2__requestSpecificData_PR_eventList,
	SmdsSigned2__requestSpecificData_PR_pushServiceRegistrationResult
	/* Extensions may appear below */
	
} SmdsSigned2__requestSpecificData_PR;

/* Forward declarations */
struct EventRecordV3;

/* SmdsSigned2 */
typedef struct SmdsSigned2 {
	TransactionId_t	 transactionId;
	struct SmdsSigned2__requestSpecificData {
		SmdsSigned2__requestSpecificData_PR present;
		union SmdsSigned2__requestSpecificData_u {
			struct SmdsSigned2__requestSpecificData__eventList {
				struct SmdsSigned2__requestSpecificData__eventList__eventEntries {
					A_SEQUENCE_OF(struct EventRecordV3) list;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} eventEntries;
				OCTET_STRING_t	*ecId	/* OPTIONAL */;
				GeneralizedTime_t	*pushServiceRefreshTime	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} eventList;
			struct SmdsSigned2__requestSpecificData__pushServiceRegistrationResult {
				GeneralizedTime_t	*pushServiceRefreshTime	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} pushServiceRegistrationResult;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} requestSpecificData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SmdsSigned2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SmdsSigned2;
extern asn_SEQUENCE_specifics_t asn_SPC_SmdsSigned2_specs_1;
extern asn_TYPE_member_t asn_MBR_SmdsSigned2_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EventRecordV3.h"

#endif	/* _SmdsSigned2_H_ */
#include <asn_internal.h>
