/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "TransferEimPackageRequest.h"

static asn_oer_constraints_t asn_OER_type_TransferEimPackageRequest_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TransferEimPackageRequest_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  3 }	/* (0..3,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TransferEimPackageRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageRequest, choice.euiccPackageRequest),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageRequest, choice.ipaEuiccDataRequest),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpaEuiccDataRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipaEuiccDataRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageRequest, choice.eimAcknowledgements),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EimAcknowledgements,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimAcknowledgements"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageRequest, choice.profileDownloadTriggerRequest),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileDownloadTriggerRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileDownloadTriggerRequest"
		},
};
static const ber_tlv_tag_t asn_DEF_TransferEimPackageRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (78 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TransferEimPackageRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 }, /* euiccPackageRequest */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 1, 0, 0 }, /* ipaEuiccDataRequest */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 2, 0, 0 }, /* eimAcknowledgements */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 3, 0, 0 } /* profileDownloadTriggerRequest */
};
asn_CHOICE_specifics_t asn_SPC_TransferEimPackageRequest_specs_1 = {
	sizeof(struct TransferEimPackageRequest),
	offsetof(struct TransferEimPackageRequest, _asn_ctx),
	offsetof(struct TransferEimPackageRequest, present),
	sizeof(((struct TransferEimPackageRequest *)0)->present),
	asn_MAP_TransferEimPackageRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TransferEimPackageRequest = {
	"TransferEimPackageRequest",
	"TransferEimPackageRequest",
	&asn_OP_CHOICE,
	asn_DEF_TransferEimPackageRequest_tags_1,
	sizeof(asn_DEF_TransferEimPackageRequest_tags_1)
		/sizeof(asn_DEF_TransferEimPackageRequest_tags_1[0]), /* 1 */
	asn_DEF_TransferEimPackageRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransferEimPackageRequest_tags_1)
		/sizeof(asn_DEF_TransferEimPackageRequest_tags_1[0]), /* 1 */
	{ &asn_OER_type_TransferEimPackageRequest_constr_1, &asn_PER_type_TransferEimPackageRequest_constr_1, CHOICE_constraint },
	asn_MBR_TransferEimPackageRequest_1,
	4,	/* Elements count */
	&asn_SPC_TransferEimPackageRequest_specs_1	/* Additional specs */
};

