/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifyProfileRecoveryRequest_H_
#define	_VerifyProfileRecoveryRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SmdpSigned4.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VerifyProfileRecoveryRequest */
typedef struct VerifyProfileRecoveryRequest {
	SmdpSigned4_t	 smdpSigned4;
	OCTET_STRING_t	 smdpSignature4;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifyProfileRecoveryRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifyProfileRecoveryRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifyProfileRecoveryRequest_H_ */
#include <asn_internal.h>
