/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#include "VerifySmdpResponseRequest.h"

static asn_TYPE_member_t asn_MBR_VerifySmdpResponseRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct VerifySmdpResponseRequest, smdpSigned6),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned6"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct VerifySmdpResponseRequest, smdpSignature6),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature6"
		},
};
static const ber_tlv_tag_t asn_DEF_VerifySmdpResponseRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (96 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_VerifySmdpResponseRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* smdpSigned6 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 } /* smdpSignature6 */
};
static asn_SEQUENCE_specifics_t asn_SPC_VerifySmdpResponseRequest_specs_1 = {
	sizeof(struct VerifySmdpResponseRequest),
	offsetof(struct VerifySmdpResponseRequest, _asn_ctx),
	asn_MAP_VerifySmdpResponseRequest_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_VerifySmdpResponseRequest = {
	"VerifySmdpResponseRequest",
	"VerifySmdpResponseRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_VerifySmdpResponseRequest_tags_1,
	sizeof(asn_DEF_VerifySmdpResponseRequest_tags_1)
		/sizeof(asn_DEF_VerifySmdpResponseRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_VerifySmdpResponseRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_VerifySmdpResponseRequest_tags_1)
		/sizeof(asn_DEF_VerifySmdpResponseRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_VerifySmdpResponseRequest_1,
	2,	/* Elements count */
	&asn_SPC_VerifySmdpResponseRequest_specs_1	/* Additional specs */
};

