/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifySmdpResponseResponse_H_
#define	_VerifySmdpResponseResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerifySmdpResponseResponse_PR {
	VerifySmdpResponseResponse_PR_NOTHING,	/* No components present */
	VerifySmdpResponseResponse_PR_verifySmdpResponseOk,
	VerifySmdpResponseResponse_PR_verifySmdpResponseError
	/* Extensions may appear below */
	
} VerifySmdpResponseResponse_PR;
typedef enum VerifySmdpResponseResponse__verifySmdpResponseError {
	VerifySmdpResponseResponse__verifySmdpResponseError_invalidSignature	= 2,
	VerifySmdpResponseResponse__verifySmdpResponseError_noSession	= 4,
	VerifySmdpResponseResponse__verifySmdpResponseError_invalidTransactionId	= 5,
	VerifySmdpResponseResponse__verifySmdpResponseError_undefinedError	= 127
} e_VerifySmdpResponseResponse__verifySmdpResponseError;

/* VerifySmdpResponseResponse */
typedef struct VerifySmdpResponseResponse {
	VerifySmdpResponseResponse_PR present;
	union VerifySmdpResponseResponse_u {
		NULL_t	 verifySmdpResponseOk;
		long	 verifySmdpResponseError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifySmdpResponseResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifySmdpResponseResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifySmdpResponseResponse_H_ */
#include <asn_internal.h>
