/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifyProfileRecoveryResponse_H_
#define	_VerifyProfileRecoveryResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerifyProfileRecoveryResponse_PR {
	VerifyProfileRecoveryResponse_PR_NOTHING,	/* No components present */
	VerifyProfileRecoveryResponse_PR_verifyProfileRecoveryOk,
	VerifyProfileRecoveryResponse_PR_verifyProfileRecoveryError
	/* Extensions may appear below */
	
} VerifyProfileRecoveryResponse_PR;
typedef enum VerifyProfileRecoveryResponse__verifyProfileRecoveryError {
	VerifyProfileRecoveryResponse__verifyProfileRecoveryError_invalidSignature	= 2,
	VerifyProfileRecoveryResponse__verifyProfileRecoveryError_noSession	= 4,
	VerifyProfileRecoveryResponse__verifyProfileRecoveryError_invalidTransactionId	= 5,
	VerifyProfileRecoveryResponse__verifyProfileRecoveryError_undefinedError	= 127
} e_VerifyProfileRecoveryResponse__verifyProfileRecoveryError;

/* VerifyProfileRecoveryResponse */
typedef struct VerifyProfileRecoveryResponse {
	VerifyProfileRecoveryResponse_PR present;
	union VerifyProfileRecoveryResponse_u {
		NULL_t	 verifyProfileRecoveryOk;
		long	 verifyProfileRecoveryError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifyProfileRecoveryResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifyProfileRecoveryResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifyProfileRecoveryResponse_H_ */
#include <asn_internal.h>
