/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifySmdsResponseResponse_H_
#define	_VerifySmdsResponseResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerifySmdsResponseResponse_PR {
	VerifySmdsResponseResponse_PR_NOTHING,	/* No components present */
	VerifySmdsResponseResponse_PR_verifySmdsResponseOk,
	VerifySmdsResponseResponse_PR_verifySmdsResponseError
	/* Extensions may appear below */
	
} VerifySmdsResponseResponse_PR;
typedef enum VerifySmdsResponseResponse__verifySmdsResponseError {
	VerifySmdsResponseResponse__verifySmdsResponseError_invalidSignature	= 2,
	VerifySmdsResponseResponse__verifySmdsResponseError_noSession	= 4,
	VerifySmdsResponseResponse__verifySmdsResponseError_invalidTransactionId	= 5,
	VerifySmdsResponseResponse__verifySmdsResponseError_undefinedError	= 127
} e_VerifySmdsResponseResponse__verifySmdsResponseError;

/* VerifySmdsResponseResponse */
typedef struct VerifySmdsResponseResponse {
	VerifySmdsResponseResponse_PR present;
	union VerifySmdsResponseResponse_u {
		NULL_t	 verifySmdsResponseOk;
		long	 verifySmdsResponseError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifySmdsResponseResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifySmdsResponseResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifySmdsResponseResponse_H_ */
#include <asn_internal.h>
