/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifyDeviceChangeRequest_H_
#define	_VerifyDeviceChangeRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SmdpSigned5.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VerifyDeviceChangeRequest */
typedef struct VerifyDeviceChangeRequest {
	SmdpSigned5_t	 smdpSigned5;
	OCTET_STRING_t	 smdpSignature5;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifyDeviceChangeRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifyDeviceChangeRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifyDeviceChangeRequest_H_ */
#include <asn_internal.h>
