/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_VerifyDeviceChangeResponse_H_
#define	_VerifyDeviceChangeResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DeviceChangeData.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VerifyDeviceChangeResponse_PR {
	VerifyDeviceChangeResponse_PR_NOTHING,	/* No components present */
	VerifyDeviceChangeResponse_PR_verifyDeviceChangeOk,
	VerifyDeviceChangeResponse_PR_verifyDeviceChangeError
	/* Extensions may appear below */
	
} VerifyDeviceChangeResponse_PR;
typedef enum VerifyDeviceChangeResponse__verifyDeviceChangeError {
	VerifyDeviceChangeResponse__verifyDeviceChangeError_invalidSignature	= 2,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_disallowedByPolicy	= 3,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_noSession	= 4,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_invalidTransactionId	= 5,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_unsupportedCrtValues	= 6,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_invalidData	= 7,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_profileNotInDisabledState	= 8,
	VerifyDeviceChangeResponse__verifyDeviceChangeError_undefinedError	= 127
} e_VerifyDeviceChangeResponse__verifyDeviceChangeError;

/* VerifyDeviceChangeResponse */
typedef struct VerifyDeviceChangeResponse {
	VerifyDeviceChangeResponse_PR present;
	union VerifyDeviceChangeResponse_u {
		DeviceChangeData_t	 verifyDeviceChangeOk;
		long	 verifyDeviceChangeError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VerifyDeviceChangeResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VerifyDeviceChangeResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _VerifyDeviceChangeResponse_H_ */
#include <asn_internal.h>
